- consensus/bor/bor.go
- consensus/bor/clerk.go
> check bor chain id for commit span and state

- accounts/abi/abi.go
Related to https://github.com/ethereum/go-ethereum/pull/20482/files
> fix abigen to create pure/view methods

- .github/workflows/dockerimage.yml
added BOR docker push github actions workflow
> added github actions workflow for BOR docker push

- core/types/bor_receipt.go
> Making use of constant

- eth/tracers/api.go
> fix typo in tracers/api.go

- .github/workflows/ci.yml
- Dockerfile
- Dockerfile.alltools
* Cleanup apk caches after install
* Pin alpine versions for predictable builds
> Apply best practices to Dockerfile

- Dockerfile
- Dockerfile.release
Standardize Dockerfile between projects (Heimdall) and remove not necessary tini package.
> Small tweeks to Dockerfiles

- core/blockchain.go
This PR fixes the writing of ancient bor receipts.
> Fix ancestor bor receipts

- command/server/proto/server.pb.go
- command/server/proto/server.proto
- command/server/service.go
- command/server/service_test.go
- command/status.go
This PR adds a the forks to the status command.
> Add forks to status

- internal/ethapi/api.go
https://github.com/ethereum/go-ethereum/issues/23762
> fix sender pending txn

- internal/cli/bor_fingerprint.go
- internal/cli/command.go
Added bor fingerprint command to the new CLI. It works offline and shows all the properties listed in https://linear.app/matic/issue/POS-55/bor-fingerprint.
> Added bor fingerprint

- builder/files/genesis-testnet-v4.json
- internal/cli/server/chains/mumbai.go
This change corresponds to the change in launch repo: https://github.com/maticnetwork/launch/commit/33ef63852a87f1ad9662c64081cbfdbadeb4bb0d
> Modify period and backup multiplier for Mumbai testnet config

- .github/workflows/ci.yml
- .golangci.yml
https://linear.app/matic/issue/POS-501/fix-new-from-rev
> Fix new-from-rev

- builder/files/bor.service
- internal/cli/server/config.go
- params/version.go
This includes two minor fixes:
* Change version parameter to 0.3.0
* Match default parameters to mainnet in new CLI and service file
> Merge fixes from v0.3.0-candidate to develop

- core/tests/blockchain_repair_test.go
- miner/fake_miner.go
- miner/test_backend.go
- miner/worker.go
- miner/worker_test.go
> Mining benchmark

- consensus/bor/bor.go
- consensus/bor/contract/client.go
- consensus/bor/heimdall.go
- consensus/bor/heimdall/client.go
- consensus/bor/heimdall/span/spanner.go
- consensus/bor/span.go
- consensus/bor/span_mock.go
- consensus/bor/statefull/processor.go
- core/tests/blockchain_repair_test.go
- eth/backend.go
- eth/handler_bor.go
- miner/fake_miner.go
- miner/worker_test.go
- tests/bor/bor_test.go
- tests/bor/mocks/IHeimdallClient.go
as a developer I need an API that provides me cancellation
> add context to Fetch* methods

- consensus/bor/valset/validator_set_test.go
Added Test-Cases for the validator set mechanisms. This tests the consistency of the updating mechanism of the power and priority of the validators in the validator set.
Link to [Jira Task](https://polygon.atlassian.net/browse/POS-615?atlOrigin=eyJpIjoiMzAyYjI5ODNmNTBhNDgzMmExZGQ5YzFmNWZhODBkN2MiLCJwIjoiaiJ9).
> Added valSet testcases

- .goreleaser.yml
- builder/files/bor-post-install.sh
- builder/files/bor.service
This change will check and create a new 'bor' user when a bor binary is installed on a user's machine.
> Add 'bor' user during package installation

- core/blockchain.go
- core/blockstm/executor.go
- core/blockstm/executor_test.go
- core/blockstm/status.go
- core/parallel_state_processor.go
- core/state/statedb.go
- core/state_processor_test.go
Refactor blockstm executor into a structure that can execute transactions step by step. This enables us to write property based tests for the executor.
> Refactor blockstm executor

- consensus/bor/bor.go
- scripts/getconfig.sh
This PR cherry picks 2 PR's from develop to merge to QA for release.
> Merge commits to qa

- builder/files/config.toml
- docs/cli/removedb.md
- docs/cli/server.md
- internal/cli/server/config.go
- internal/cli/server/flags.go
- scripts/getconfig.go
* add support for bor.logs flag in new-cli
* handle bor.withoutheimdall flag commenting in conversion script
> internal/cli: add support for bor.logs flag in new-cli (#541)

- core/bench_test.go
This PR fixes a small bug encountered during executing the benchmark tests in `core` .
> Fix Benchmark test

- cmd/geth/config.go
- docs/README.md
- docs/config.md
- internal/cli/server/config.go
- internal/cli/server/server.go
- metrics/metrics.go
- scripts/getconfig.sh
Cherry-pick https://github.com/maticnetwork/bor/pull/560 into qa.
> Force load default tracers

- consensus/bor/statefull/processor.go
- core/vm/interface.go
- eth/tracers/api.go
- eth/tracers/api_bor.go
- eth/tracers/api_test.go
Merge https://github.com/maticnetwork/bor/pull/547 into qa.
> Add state sync transaction to debug_trace functions.

- builder/files/config.toml
- docs/cli/server.md
- internal/cli/server/config.go
- internal/cli/server/flags.go
- scripts/getconfig.go
> Removed vhosts for ws and replaced cors with origins

- builder/files/config.toml
- docs/cli/server.md
- internal/cli/server/config.go
- internal/cli/server/flags.go
- scripts/getconfig.go
Merge [PR 574](https://github.com/maticnetwork/bor/pull/574) into qa.
> Removed vhosts for ws and replaced cors with origins (#574)

- params/version.go
> Bump version to stable

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
Bumping version in control files. 
> Bumping control file versions

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
Bump bor version in control files for v0.3.3 mainnet release. 
> packaging: bump bor version in control files

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
> version change

- internal/cli/debug_pprof.go
- internal/cli/server/server.go
In this PR, we added mutex profile generation using pprof.
> Add : mutex pprof profile

- internal/ethapi/api.go
- miner/worker.go
Cherry picks https://github.com/maticnetwork/bor/pull/736 and https://github.com/maticnetwork/bor/pull/728 from develop. 
> Cherry-pick changes from develop

- .github/ISSUE_TEMPLATE/bug.md
- README.md
Updated readme to use new Wiki link.
> Update wiki link

- core/tests/blockchain_repair_test.go
- miner/test_backend.go
- miner/worker_test.go
In this PR, we introduce unit testcase for commit interrupt feature. ( `TestCommitInterruptExperimentBor` )
> add : testcase for CommitInterruptExperiment

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
> dev: chg: version bump for v0.3.9-beta

- consensus/bor/api.go
The PR aims to address #582 . The `bor` RPC methods `bor_getAuthor`, `bor_getSnapshotProposer` and `bor_getSnapshotProposerSequence` will now be invokable via block hash along with block number.
**Minor Note to the release conductor**:  Let's please add the feature changes to the API in the notes for the next release, albeit non-breaking.
> consensus/bor: modify bor RPC methods

- core/blockchain.go
- core/blockchain_test.go
- core/blockstm/executor.go
- core/blockstm/executor_test.go
- core/parallel_state_processor.go
Allows block import to use regular processor and parallel processor at the same time. 
> Run serial and parallel processor at the same time

- eth/fetcher/block_fetcher.go
This PR contains the fix to the peering issues (#837).
> eth/fetcher: if peers never respond, drop them (#837)

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
> dev: chg: bump version to beta-2 for v0.3.9

- .github/matic-cli-config.yml
Change `contracts` branch for the ci to use node-16.
> dev: chg: use node-16 contracts branch

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
Bump version for `v0.3.9-beta-3`
> v0.3.9-beta-3 version bump

- scripts/updateVersion.sh
Instead of manually updating the version across all the files, use this script and provide all the 4 components of the version, and it will update the version across all the 7 files.
```
$ ./scripts/updateVersion.sh
```
```
The version is of form - VersionMajor.VersionMinor.VersionPatch-VersionMeta
Let's take 0.3.4-beta as an example. Here:
* VersionMajor is - 0
* VersionMinor is - 3
* VersionPatch is - 4
* VersionMeta is  - beta
Now, enter the new version step-by-step below:
* VersionMajor: 0
* VersionMinor: 3
* VersionPatch: 8
* VersionMeta (optional, press enter if not needed): beta  
The new version is: 0.3.8-beta
Updating Version Done
```
> Added a script to increase the version

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
Version bump for `beta-4` on `v0.3.9`
> beta version bump

- eth/protocols/eth/dispatcher.go
This pull request includes a minor modification that involves removing the request from the tracker's list when it is canceled.
- [ ✔] Bugfix (non-breaking change that solves an issue)
All the nodes should include this change
- [ ✔] I have added at least 2 reviewer or the whole pos-v1 team
- [✔ ] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply
> eth/protocols/eth: fix: remove cancelled request from tracker's list

- .github/pull_request_template.md
Adds 2 more elements to the PR checklist.
> dev: add: additional elements in PR checklist

- core/state/journal.go
An address's nonce and balance will get updated even if its transaction is reverted. Therefore, we need to keep balance and nonce in write list in order to check the transaction's validity in parallel execution.
> Keep nonce and balance in write list even if the transaction is reverted

- builder/files/genesis-testnet-v4.json
- internal/cli/server/chains/mumbai.go
- internal/cli/server/chains/test_files/chain_legacy_test.json
- internal/cli/server/chains/test_files/chain_test.json
- params/config.go
Adds Indore HF block number. As well as sets parallel universe block (for parallel EVM) to 0.
> Added IndoreBlock for Mumbai chain

- builder/files/genesis-testnet-v4.json
- internal/cli/server/chains/mumbai.go
- internal/cli/server/chains/test_files/chain_legacy_test.json
- internal/cli/server/chains/test_files/chain_test.json
- params/config.go
> Updated indore block for mumbai

- params/config.go
> Fixed MVHashMap being enabled even when paralellUniverse is set to 0

- consensus/bor/bor_test.go
- core/chain_makers.go
- core/rawdb/accessors_chain.go
- core/rawdb/ancient_scheme.go
- core/rawdb/bor_receipt.go
- core/rawdb/freezer.go
- core/state_transition.go
- core/txpool/txpool.go
- core/types/block_test.go
- eth/backend.go
- eth/protocols/snap/sync_test.go
- eth/tracers/internal/tracetest/calltrace_test.go
- eth/tracers/internal/tracetest/testdata/call_tracer/inner_revert_reason.json
- miner/worker.go
- params/config.go
This PR fixes the nil pointer dereference errors which popped up after incorporating upstream changes from geth.
> Fix nil pointer dereference errors in tests post upstream merge changes

- builder/files/genesis-mainnet-v1.json
- internal/cli/server/chains/mainnet.go
- params/config.go
Continuation on #913 
https://polygonscan.com/block/countdown/44934656
> Updated indore block to 44934656 for mainnet

- consensus/bor/bor_test.go
- core/rawdb/accessors_chain.go
- core/rawdb/ancient_scheme.go
- core/rawdb/bor_receipt.go
- core/rawdb/freezer.go
- core/state_transition.go
- core/txpool/txpool.go
- core/types/block_test.go
- eth/backend.go
- eth/protocols/snap/sync_test.go
- eth/tracers/internal/tracetest/calltrace_test.go
- eth/tracers/internal/tracetest/testdata/call_tracer/inner_revert_reason.json
> Revert "Fix nil pointer dereference errors in tests post upstream merge changes"

- cmd/clef/main.go
- go.mod
- go.sum
- node/node.go
- node/rpcstack.go
- rpc/client.go
- rpc/client_test.go
- rpc/endpoints.go
- rpc/execution_pool.go
- rpc/handler.go
- rpc/http_test.go
- rpc/inproc.go
- rpc/ipc.go
- rpc/metrics.go
- rpc/server.go
- rpc/server_test.go
- rpc/subscription_test.go
- rpc/testservice_test.go
- rpc/websocket_test.go
This PR adds metrics for execution pool (workerpool) used in RPC server to handle requests. It adds the following metrics. 
1. Total number of workers running at any time / total requests being processed at any time.
2. Total number of requests present in waiting queue at any time. 
3. Rate of processing of requests per 5s
Note that this PR depends on https://github.com/JekaMas/workerpool/pull/3. Update the `go.mod` and `go.sum` files before merging. 
Please complete this section with …
> rpc: add execution pool metrics

- .github/workflows/packager.yml
- packaging/templates/systemd/bor_bootnode.service
Fixed copy name for the bor_boornode.service file in the packager.yml.
Update the bor_bootnode.service file to contain the current values being used for bootnode. Old ExecStart values were no longer valid as changes have made them obsolete.
- [ x] Bugfix (non-breaking change that solves an issue)
Please post additional comments in this section if you have them, …
> Fixes for bootnode

- .github/workflows/stale.yml
> exempt draft PRs

- Makefile
When shuffled, tests sometimes fail due to statefulness. We had to rerun tests due to this intermittent failures. Disabling shuffling until the statefulness is removed from unit tests.
> Disable shuffling in unit test

- .github/workflows/packager.yml
End of Life for 18.04 support, all builds are compatible with Ubuntu 20.04 and newer. 
Removes the dedicated runner hosted by Polygon, uses Github runner on 20.04
> EOL 18.04 Support 

- .github/workflows/ci.yml
Currently in bor, lots of independent checks like build, lint, running unit and integration tags happen in a single job which consumes a lot of time. This PR creates new jobs for each of these process to reduce the CI time. 
> .github/workflows: run more parallel CI jobs

- trie/trie.go
Fixed concurrent map read and map write issue introduced during the upstream merge.
> Fix panic - added mutex to trie.tracer

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
> bump version

- packaging/templates/mainnet-v1/archive/config.toml
- packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml
- packaging/templates/mainnet-v1/sentry/validator/bor/config.toml
With this PR we hardcode some recommended values in the mainnet default configs for `archive`, `sentry` and `validator` nodes.
More info available at [the forum post](https://forum.polygon.technology/t/recommended-peer-settings-for-mainnet-nodes/13018)
> mainnet recommended peer settings

- miner/worker.go
Do not hardcode EnableMVHashMap as false
> worker: (Block-STM) Do not hardcode EnableMVHashMap as false

- .github/workflows/codeql.yml
Install `go` as part of the CodeQL workflow by using the version taken from `go.mod`
> install go in CodeQL workflow

- consensus/bor/bor.go
- consensus/errors.go
> Shanghai fixes

- tests/bor/helper.go
Fix integration test `TestInsertingSpanSizeBlocks`, which started failing after commit https://github.com/maticnetwork/bor/commit/d0abdcb18864c1e6193c6ee65f619f4741d6dbeb.
> Set withdraw to nil when building blocks for integration tests

- builder/files/config.toml
- docs/cli/example_config.toml
- docs/cli/server.md
- internal/cli/server/config.go
- internal/cli/server/flags.go
- packaging/templates/mainnet-v1/archive/config.toml
- packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml
- packaging/templates/mainnet-v1/sentry/validator/bor/config.toml
- packaging/templates/mainnet-v1/without-sentry/bor/config.toml
- packaging/templates/testnet-v4/archive/config.toml
- packaging/templates/testnet-v4/sentry/sentry/bor/config.toml
- packaging/templates/testnet-v4/sentry/validator/bor/config.toml
- packaging/templates/testnet-v4/without-sentry/bor/config.toml
Added cache.blocklogs (FilterLogCacheSize) flag
> Added cache.blocklogs (FilterLogCacheSize) flag

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
In this PR, we bump the bor version and add meta tag = `amoy` to the code.
> bump : version meta to amoy

- .github/workflows/ci.yml
This PR updates `matic-cli` according to the changes made in [this PR](https://github.com/maticnetwork/matic-cli/pull/212)
> Update matic-cli in CI

- params/config.go
> chg: make HF consistent

- core/vm/contracts.go
> core/vm: remove kzg precompile

- cmd/evm/testdata/3/readme.md
- cmd/evm/testdata/4/readme.md
- core/blockchain.go
- core/blockstm/mvhashmap.go
- core/parallel_state_processor.go
- core/state/pruner/pruner.go
- core/vm/interpreter.go
- eth/backend.go
- miner/worker_test.go
- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
> Revert "fix bug: should use Lock when mutating the flag"

- internal/cli/server/chains/amoy.go
- params/config.go
Fixed the following error in CI
```
params/config.go:269:4: unknown field ParallelUniverseBlock in struct literal of type BorConfig
```
> Removed ParallelUniverseBlock from amoyTestnet

- miner/worker.go
Fixed the increase in go-routines in non-validating nodes
Only enable the go-routine to update dependencies if the worker is enabled.
> blockstm: hot fix: only enable go routine to update dependencies if worker is enabled

- miner/worker.go
This change will check commit interrupt signal coming from other channels, e.g. newHead, reSubmit, before checking transaction level interrupt. This is to fix a corner case where an interrupt signal coming from another channel getting intercepted by transaction level interrupt, which resulted in an uncleaned state (potentially deadlock).
Please complete this section with the steps you performed if you ran manual tests for …
> [Bug fix] Re-prioritize commit interrupts

- integration-tests/bor_health.sh
- integration-tests/smoke_test.sh
Porting changes from https://github.com/maticnetwork/bor/pull/1173 to `master` to fix the CI
> fix: root folder for docker integration tests (#1173)

- builder/files/genesis-mainnet-v1.json
- internal/cli/server/chains/mainnet.go
- params/config.go
Finalize mainnet cancun/napoli HF block number to block 54876000
> Finalize mainnet cancun/napoli HF block number

- eth/tracers/api.go
- eth/tracers/api_bor.go
- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
Includes the changes to fix in block tracing
> V1.2.8 beta candidate

- miner/worker.go
In case where commitTransactions is interrupted, it will exit without properly closing chDeps, leaving the dependency calculation goroutine hanging. This commit fixes this issue.
> Properly close deps channel

- internal/ethapi/api.go
- internal/ethapi/api_test.go
- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
Merge "V1.3.0 beta candidate" into develop
> merge "V1.3.0 beta candidate" into develop

- consensus/bor/valset/validator_set.go
- core/blockstm/mvhashmap_test.go
- eth/handler_eth_test.go
- internal/cli/dumpconfig.go
- tests/bor/bor_test.go
- tests/bor/helper.go
> chore: fix some comments

- internal/jsre/deps/web3.js
fix a typo: `overrwritten`->`overwritten`
> chore: fix typos

- eth/gasprice/feehistory.go
This PR fixes the percentile validation in eth_feeHistory
> eth/gasprice: fix percentile validation in eth_feeHistory

- eth/bor_checkpoint_verifier.go
- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
Cancel pending requests in downloader before rewinding chain.
> V1.3.1 beta candidate

- eth/handler.go
- eth/sync.go
In the [recent upstream](https://github.com/maticnetwork/bor/releases/tag/v1.3.0-beta-2), [this PR](https://github.com/ethereum/go-ethereum/pull/28171) was included. As a result of that we observed that node went into snap sync mode. We do not support snap sync at the moment, so in this PR, I have explicitly commented the code were bor could get into snap-sync mode.
***Please note that that geth PR is important one when running a PBSS node, so in the future, we will have to find a workaround for the scenarios where the associated head state is missing in PBSS.***
In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it (e.g. by adding a flag …
> eth: explicitly commented the code were bor could get into snap-sync mode

- ethstats/ethstats.go
Observed that the node panics rarely and this was because error handling was not done properly.
> ethstats: added error handeling in ethstats.go which prevents node to panic

- ethstats/ethstats.go
It's weird, but it's possible that the block is nil here even though the check for error is done above.
> Fix panic when fetching block in case of reorg

- core/txpool/legacypool/legacypool.go
- core/txpool/legacypool/legacypool_test.go
- docs/cli/example_config.toml
- docs/cli/server.md
- eth/backend.go
- eth/catalyst/api_test.go
- eth/gasprice/gasprice.go
- internal/cli/server/config.go
- internal/cli/server/config_test.go
- internal/cli/server/server.go
- internal/cli/server/testdata/default.toml
- miner/miner.go
- miner/worker_test.go
- packaging/templates/testnet-amoy/archive/config.toml
- packaging/templates/testnet-amoy/sentry/sentry/bor/config.toml
- packaging/templates/testnet-amoy/sentry/validator/bor/config.toml
- packaging/templates/testnet-amoy/without-sentry/bor/config.toml
- packaging/templates/testnet-v4/archive/config.toml
- packaging/templates/testnet-v4/sentry/sentry/bor/config.toml
- packaging/templates/testnet-v4/sentry/validator/bor/config.toml
- packaging/templates/testnet-v4/without-sentry/bor/config.toml
- params/protocol_params.go
See https://github.com/maticnetwork/bor/pull/1234
> core, eth, internal, miner, params: enforce 30gwei for gas related configs in bor

- accounts/keystore/account_cache_test.go
- accounts/keystore/keystore_test.go
> chore: fix some function names

- README.md
Updated the discord server link.
> README: Update discord link

- p2p/discover/v4_udp.go
- p2p/discover/v5_udp.go
Fixes an issue where discovery responses were not recognized.
This PR backports https://github.com/ethereum/go-ethereum/pull/29944.
Fixes an issue where discovery responses were not recognized.
> p2p/discover: unwrap 4-in-6 UDP source addresses (#29944)

- p2p/discover/table.go
cherry-picked [geth#29960](https://github.com/ethereum/go-ethereum/pull/29960) to fix `fatal error: concurrent map read and map write`
> p2p/discover: add missing lock when calling tab.handleAddNode (#29960)

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/question.md
- README.md
Point discord invite links to the latest ones. 
> README, .github: update discord links

- .github/workflows/ci.yml
- .github/workflows/govuln.yml
Update the versions for `actions/download-artifact` and `actions/upload-artifact` due to deprecations.
> Update artifacts upload/download actions version

- docs/cli/server.md
- internal/cli/server/flags.go
- internal/ethapi/api.go
Add flag discovery.dns and fix a bug in eth_getTransactionReceipt for state sync tx.
> Add discovery.dns

- .github/workflows/rpm_amoy_profile_packager.yml
- .github/workflows/rpm_mainnet_profile_packager.yml
Updating naming convention for the use of the pbss profiles for rpms
- [x ] I have added at least 2 reviewer or the whole pos-v1 team
- [x ] I have added sufficient documentation in code
> Changing names of pbss profiles for consistency in deb and rpm

- .github/workflows/rpm_amoy_profile_packager.yml
- .github/workflows/rpm_mainnet_profile_packager.yml
Updated artifact upload to actually upload the pbss profiles for rpm.
- [x ] I have added at least 2 reviewer or the whole pos-v1 team
> Updating uploader

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
Bump version 
- [x Hotfix (change that solves an urgent issue, and requires immediate attention)
> Bump version to v1.5.1

- internal/ethapi/api.go
Fixes https://github.com/maticnetwork/bor/issues/1364. Tests will be added later.
> Fix getBlockTransactionCountByNumber/Hash

- packaging/templates/package_scripts/control
- packaging/templates/package_scripts/control.arm64
- packaging/templates/package_scripts/control.profile.amd64
- packaging/templates/package_scripts/control.profile.arm64
- packaging/templates/package_scripts/control.validator
- packaging/templates/package_scripts/control.validator.arm64
- params/version.go
> Bump version to v1.5.2

- core/blockchain.go
- core/blockchain_test.go
Enables the node to bypass unexpected errors from parallel execution and use the result from serial execution instead.
> Fallback to serial execution if parallel execution fails

- params/version.go
> Backport master to develop

- consensus/bor/bor.go
- consensus/bor/heimdall/client.go
- consensus/bor/heimdall/client_test.go
- consensus/bor/heimdall/milestone/milestone.go
- consensus/bor/heimdallapp/milestone.go
- consensus/bor/heimdallgrpc/milestone.go
- eth/handler_bor.go
- eth/handler_bor_test.go
Fix responses and parsing for milestone related requests.
> Fix responses and parsing for milestone related requests.

- internal/cli/server/api_service.go
Additional checks for GRPC API endpoints.
> Additional GRPC API checks

- consensus/bor/heimdall.go
- consensus/bor/heimdall/checkpoint/checkpoint.go
- consensus/bor/heimdall/client.go
- consensus/bor/heimdall/client_test.go
- consensus/bor/heimdall/milestone/milestone.go
- consensus/bor/heimdallapp/checkpoint.go
- consensus/bor/heimdallapp/milestone.go
- consensus/bor/heimdallgrpc/checkpoint.go
- consensus/bor/heimdallgrpc/milestone.go
- eth/handler_bor.go
- eth/handler_bor_test.go
> HV2 - checkpoint, milestone: fix response

- consensus/bor/bor.go
- go.mod
- go.sum
Update to use latest types from heimdall-v2.
Change assignment of MinimalVal signer.
> Fix minimal val assignment

- consensus/bor/statefull/processor.go
When `commitSpan` failed in `ApplyMessage` we don't log or return error. We need to discuss more on whether we can return an error or not back to the root function but for now, we can surely log it. 
> consensus/bor: log err when commit span fails

- .github/workflows/ci.yml
Uses the `docker_devnet.sh` script instead of single ones.
> Simplify e2e-tests CI by using the consolidated script

- crypto/crypto.go
- params/version.go
> v1.5.5 release

- cmd/evm/runner.go
Porting https://github.com/ethereum/go-ethereum/pull/30259 into bor to solve PSF-1956.
> cmd/evm: don't overwrite sender account

- beacon/light/request/scheduler.go
- consensus/misc/eip1559/eip1559_test.go
fix some function names in comment
> chore: fix some function names in comment

- .github/workflows/amoy_deb_profiles.yml
- .github/workflows/mainnet_deb_profiles.yml
- .github/workflows/packager_deb.yml
Github is ending support for 20.04 ubuntu, updating packaging actions to use 22.04:
https://github.com/oerdnj/deb.sury.org/issues/2243
> As 20.04 is being EOL for github runner support, moving to 22.04

- .github/workflows/ci.yml
Use ubuntu 22.04 in GH actions due to EOS
> use ubuntu 22.04

- cmd/cli/main.go
- params/version.go
> feat: `bor_info` metric

- consensus/bor/heimdall.go
- consensus/bor/heimdall/client.go
- consensus/bor/heimdall/client_test.go
- consensus/bor/heimdall/metrics.go
- consensus/bor/heimdall/milestone/milestone.go
- consensus/bor/heimdallapp/milestone.go
- consensus/bor/heimdallgrpc/milestone.go
- eth/backend.go
- eth/handler_bor.go
- eth/handler_bor_test.go
- tests/bor/bor_test.go
- tests/bor/mocks/IHeimdallClient.go
Remove milestones no ack fetching.
> Remove milestone no-ack fetching

- .github/ISSUE_TEMPLATE/bug.md
- .github/pull_request_template.md
- README.md
- docs/cli/server.md
Removes usage of Mumbai from README.
> chore: Remove usage of Mumbai from README

- .github/matic-cli-config.yml
- .github/workflows/ci.yml
- integration-tests/fund_ganache_accounts.sh
> Revert "CI changes to accommodate Anvil"

- .github/matic-cli-config.yml
- .github/workflows/ci.yml
Since `matic-cli` now uses `anvil` as L1, a few changes to the CI were required. The updates include:
1. Installing Foundry  
2. Removing the funding script (`fund-anvil-account.sh`), as it is no longer required  
3. Adjusting `cd` commands for directory changes  
4. Replacing Truffle with Foundry/Forge  
These changes ensure compatibility with the new setup. …
> CI changes to accommodate Anvil

- internal/cli/server/config.go
Set WS address empty by default
> empty ws addree by default

- eth/backend.go
- eth/protocols/eth/discovery.go
- eth/protocols/eth/handler.go
- eth/protocols/snap/handler.go
https://github.com/ethereum/go-ethereum/pull/30302 broke PoS DNS discovery. Reverting it fixes the problem.
Tested on a sentry node which wasn't able to get new peers. After reverting the commit, it was able to quickly connected to 50+ peers. 
> Revert "eth: dial nodes from discv5 (#30302)"

- eth/backend.go
> Bor nil check on ws subscription

- internal/ethapi/api.go
> fix nil pointer dereference on DoCall

- consensus/bor/heimdall/checkpoint/checkpoint.go
- consensus/bor/heimdall/milestone/milestone.go
- consensus/bor/valset/validator.go
- tests/bor/bor_test.go
- tests/bor/helper.go
- tests/bor/testdata/span.json
> test(bor-hv2): fix Bor-HV2 tests

- cmd/devp2p/internal/ethtest/conn.go
- core/blockchain.go
- core/state/statedb.go
- eth/downloader/peer.go
- eth/fetcher/block_fetcher.go
- eth/fetcher/block_fetcher_test.go
- eth/handler.go
- eth/handler_eth.go
- eth/handler_wit.go
- eth/peer.go
- eth/protocols/eth/dispatcher.go
- eth/protocols/wit/handler.go
- eth/protocols/wit/handlers.go
- eth/protocols/wit/peer.go
- eth/sync.go
Add a new queue (witness) to block fetcher.
> Add witness to block fetcher

- consensus/bor/heimdall/checkpoint/checkpoint.go
- consensus/bor/heimdall/milestone/milestone.go
Fix checkpoint and milestone v2 response
> Fix checkpoint and milestone v2 response

- .github/workflows/amoy_deb_profiles.yml
- .github/workflows/mainnet_deb_profiles.yml
- .github/workflows/packager_deb.yml
Removing prerelease: true, and using make_latest: false to address a bug
> Updating packager

- core/types/block.go
Fix function name in comment
The new pr for https://github.com/maticnetwork/bor/pull/1522
> chore: fix function name in comment

- core/blockchain.go
- core/blockchain_test.go
- core/state/database.go
- eth/backend.go
- eth/downloader/queue.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- eth/fetcher/block_fetcher.go
- eth/fetcher/witness_manager.go
- eth/handler.go
- eth/handler_eth.go
- eth/handler_wit.go
- eth/peer.go
- eth/peerset.go
- eth/protocols/wit/broadcast.go
- eth/protocols/wit/peer.go
- eth/protocols/wit/peer_test.go
- eth/protocols/wit/protocol.go
- internal/cli/server/config.go
- internal/cli/server/flags.go
- triedb/database.go
This PR will enable a full node to use witness to sync a block.
> Sync block with witness in full sync

- params/config.go
- params/protocol_params.go
Added Bhilai HF and Increase BaseFeeChangeDenominator to 64 ([PIP-58](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-58.md))
> PIP-58: Increase BaseFeeChangeDenominator to 64

- core/txpool/txpool.go
- eth/backend.go
To handle this scenario I included it as `nil` on handler and properly handled each call scenario. The only one I had to generate an actual new behavior was the one regarding adding new transactions, which raises a new error.
> Disable tx pool for stateless client

- builder/files/genesis-amoy.json
- internal/cli/server/chains/amoy.go
- params/config.go
Added Bhilai (and Prague) block for Amoy
Block Number `22765056`: Expected time `Jun-11-2025 10 AM UTC (3:30 pm IST)`
> Added Bhilai (and Prague) block for Amoy

- .github/matic-cli-config.yml
- .github/workflows/ci.yml
Fixes the `ci.yml` and `matic-cli-config.yml` files.
> fix(CI): update ci and matic-cli config 

- core/blockchain.go
- core/blockchain_test.go
After veblop, a previously imported/produced block could become invalid, due to dynamic span rotation. This PR will automatically detect when this happens and rewind invalid blocks.
> Auto rewind blocks when their span rotates

- builder/files/genesis-mainnet-v1.json
- internal/cli/server/chains/mainnet.go
- params/config.go
**Bhilai Block for Mainnet is `73440256`**
**Estimated Time is** `July-1-2025 9:11:25 AM +UTC`
> Added Bhilai and Prague block for mainnet

- eth/backend.go
- eth/downloader/whitelist/milestone.go
- eth/downloader/whitelist/service.go
- eth/downloader/whitelist/service_test.go
This commit implements a fork detection mechanism in the whitelist milestone validation system to resolve synchronization issues that occur when nodes sync from new milestone with extremely low latency. The problem was that nodes on different chain forks would be unable to sync with peers due to milestone validation rejecting chains with different block hashes, leading to "mismatch error" failures.
Root Cause Analysis:
The issue was caused by chain fork lock-in where milestone validation prevented nodes stuck on wrong forks from syncing to the correct canonical chain. Debug logs revealed that different nodes had different block hashes for the same block numbers, confirming a fork scenario where milestone validation was blocking recovery.
Solution Implemented:
- Added ChainReader interface …
> Allow peer sync recovery from a wrong fork

- eth/fetcher/block_fetcher.go
- eth/fetcher/block_fetcher_race_test.go
- eth/fetcher/witness_manager.go
- eth/fetcher/witness_manager_test.go
- eth/handler_bor_test.go
Also added more unit tests for block fetcher and witness manager.
> Add mutex to block_fetcher to prevent concurrent map access

- consensus/bor/heimdall/client.go
> Fix statesync url pagination

- eth/handler_wit.go
> fix double witness insertion

- eth/handler_bor.go
> eth: added a check to prevent panic in bor handler

- builder/files/genesis-mainnet-v1.json
- consensus/bor/bor.go
- consensus/bor/heimdall/client.go
- consensus/bor/heimdallgrpc/client.go
- internal/cli/server/chains/mainnet.go
- params/config.go
- params/version.go
> V2.2.6 candidate

- eth/bor_checkpoint_verifier.go
This resolved a possible race condition when a milestone reorg happens at the same time when a validator mines a new block. The miner should be completely stopped when setHead canonical head and inserting finalized chain. Without this, a block producing node can get stuck after a reorg.
> Stop miner when reorg from milestone

- core/filtermaps/indexer.go
- core/genesis.go
- core/rawdb/accessors_indexes.go
fix inconsistent function name in comment
> chore: fix inconsistent function name in comment

- miner/miner_test.go
- miner/worker.go
- trie/hasher.go
fix some inconsistent comments
> chore: fix some inconsistent comments

- consensus/bor/bor.go
- core/blockchain.go
- core/state/statedb.go
This will resolve the missing trie node issue.
> Add all states read during finalization in witness

- integration-tests/stateless_sync_test.sh
> Change veblop HF to span start block in test

- core/blockchain.go
- core/stateless/encoding.go
- core/stateless/encoding_test.go
- core/stateless/example_test.go
- core/stateless/witness.go
- eth/api_backend.go
- eth/handler_wit.go
- eth/peer.go
- eth/peer_test.go
This PR introduces gzip compression and deduplication for witness data in Bor, reducing the size of witness objects stored and transmitted across the network.
These are the configurable params
```
type CompressionConfig struct {
Enabled          bool  // Enable/disable compression
Threshold        int   // Minimum size to consider compression
CompressionLevel int   // Gzip compression level (1-9)
UseDeduplication bool  // Enable witness optimization
}
```
- Compression Marker: Uses 0x01 for compressed, 0x00 for uncompressed
- Smart Compression: Only compresses when it actually reduces size
- Configurable Threshold: Only compresses data larger than a configurable threshold
- Code Normalization: Removes trailing zeros from bytecode
- State Deduplication: Removes empty or redundant state …
> core: witness compression

- .github/workflows/ci.yml
- Dockerfile.release
- go.mod
- `go mod tidy`
- Merged develop.
- Commented the remaining part of matic-cli e2e-tests.
> chore(stateless): go mod tidy and minor chores

- consensus/bor/bor.go
- consensus/bor/snapshot.go
- consensus/bor/span_store.go
- consensus/bor/span_store_test.go
- core/blockchain.go
- core/blockchain_test.go
- core/rawdb/accessors_state.go
- core/stateless/encoding.go
- eth/downloader/bor_downloader.go
- eth/downloader/bor_downloader_test.go
- eth/fetcher/block_fetcher_race_test.go
- eth/fetcher/block_fetcher_test.go
- eth/fetcher/witness_manager_test.go
- eth/handler_eth.go
- eth/peer.go
- eth/peer_test.go
- eth/peerset.go
- eth/protocols/snap/sync_test.go
- eth/protocols/wit/handler.go
- eth/protocols/wit/protocol.go
- internal/ethapi/api.go
Fixing lint. It helped finding a potential bug on `witReqs` appending.
> Fix lint issues

- .github/actions/kurtosis-pre-run/action.yml
- .github/configs/kurtosis-e2e.yml
- .github/workflows/kurtosis-e2e.yml
- integration-tests/kurtosis_smoke_test.sh
Bump kurtosis-cli, foundry, and kurtosis-pos.
> chore: bump kurtosis

- .github/actions/kurtosis-pre-run/action.yml
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- eth/handler.go
- integration-tests/apply_global_network_latency.sh
- integration-tests/kurtosis_stateless_test.sh
- integration-tests/kurtosis_test_utils.sh
- integration-tests/rotate_current_block_producer.sh
- internal/cli/server/config.go
- internal/cli/server/flags.go
This PR will a few more e2e tests to CI. 
Also moved witness flags to a dedicated section.
> Stateless sync network chaos tests

- core/rawdb/bor_receipt.go
This PR aims to prioritize Key Value Reads on Bor Receitps over the ones from Ancient db.
No breaks
> core: Key-Value Priority Read on BorReceipts

- core/blockchain.go
- miner/worker.go
- tests/bor/bor_api_test.go
- tests/bor/bor_test.go
- tests/bor/helper.go
> Fix integration tests in stateless_sync

- .github/workflows/kurtosis-e2e.yml
- .github/workflows/kurtosis-stateless-e2e.yml
Post-merge `stateless_sync` branch chores.
> ci: post merge chores

- core/evm.go
- core/parallel_state_processor.go
- internal/cli/server/chains/amoy.go
- internal/cli/server/chains/mumbai.go
- miner/worker.go
- params/config.go
- params/config_test.go
- tests/bor/fee_receiver_change_test.go
This PR enables coinbase to be a different address, which is specified in the genesis, from the block producer. The motivation is to redirect all tx fees in veblop era to a smart contract address, where the fee could be redistributed based on certain rules.
> Customizable coinbase address

- builder/files/genesis-amoy.json
- consensus/bor/bor.go
- consensus/bor/span_store.go
- consensus/bor/span_store_test.go
- internal/cli/server/chains/amoy.go
- params/config.go
Add validator byte check back to header validation. This prevents validators from accepting blocks that failed to include validator bytes.
Besides the validation, also added a new check to ensure the span retrieved from span store will always contain at least one block producer. 
Please post additional comments in this section if you have them, otherwise delete …
> Ensure validator bytes are correctly verified prior Rio

- consensus/bor/bor_test.go
This PR adds UTs for some veblop specific functions
> consensus: add TestPerformSpanCheck,TestGetVeBlopSnapshot and TestSnapshot

- .github/workflows/ci.yml
- .github/workflows/go.yml
- .github/workflows/govulncheck.yml
- .github/workflows/packager_deb.yml
- .github/workflows/release.yml
- core/rawdb/milestone.go
- core/txpool/legacypool/list.go
- docs/cli/README.md
- docs/cli/purge-whitelisted-entries.md
- docs/cli/server.md
- eth/backend.go
- eth/bor_checkpoint_verifier.go
- eth/downloader/bor_downloader_test.go
- eth/downloader/whitelist/checkpoint.go
- eth/downloader/whitelist/finality.go
- eth/downloader/whitelist/milestone.go
- eth/downloader/whitelist/service.go
- eth/downloader/whitelist/service_test.go
- eth/ethconfig/config.go
- eth/handler_bor.go
- eth/sync.go
- ethstats/ethstats.go
- internal/cli/command.go
- internal/cli/purge_whitelisted_entries.go
- internal/cli/server/config.go
- internal/cli/server/flags.go
- params/version.go
> v2.2.11 to master

- .github/workflows/kurtosis-e2e.yml
> chore: bump kurtosis-pos
