0xPolygon/bor

cmd/bor/chaincmd.go, cmd/utils/flags.go, eth/backend.go
Fixes #27 
Steps:
- Keep node1 running awhile, then kill it.
- Export state (all following commands from `bor-devnet` dir)
```
bor --datadir node1 export state.json ../genesis-contracts/genesis.json
```
- Create node and import state
```
bor --datadir node4 init ../genesis-contracts/genesis.json
cp keystore4/* node4/keystore/
bor --datadir node4 import state.json ../genesis-contracts/genesis.json
```
=> MAT-872: Fix import/export state with bor

consensus/bor/api.go, consensus/bor/bor.go, consensus/bor/bor_test/helper.go, consensus/bor/errors.go, consensus/bor/merkle.go, eth/api_backend.go, go.mod, go.sum, internal/ethapi/api.go, internal/ethapi/backend.go, internal/web3ext/web3ext.go, les/api_backend.go
JSON RPC API Reference:
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getRootHash","params":["0x1", "0xa"], "id":1}' http://localhost:8545
Over websocket,
wscat -c ws://localhost:8585
{"id":1, "method":"eth_getRootHash", "params":["0x1", "0xa"]}
```
Over IPC:
```
bor attach node1/bor.ipc
> bor.getRootHash(1, 10)
```
Expected response:
```
{"jsonrpc":"2.0","id":1,"result":"BXy0SRpYza0Uu42EOY8dIHXlW94HBjLBcLQu+XbIA7Q="}
```
=> new: Add bor.getRootHash(start, end) api method (MAT-1302)

.github/workflows/linuxpackage.yml
With these changes, the validator will be able to access logs using `journalctl` command: https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs
=> chg: use default service logs instead of custom files

.github/workflows/linuxpackage.yml
With this PR, Bor Linux package will support different node types:
1. `sentry` - Sentry node
2. `validator` - Validator with sentry node
3. `validator-without-sentry` - Validator without sentry node
To select node type, edit `NODE_TYPE` in  `/etc/bor/metadata` after package is installed. Possible value for `NODE_TYPE`: `sentry`, `validator` and `vaidator-without-sentry`
=> new: add options to setup different node types

eth/filters/bor_filter.go
Issue: Blockhash based filter throwing an error when bor block receipt doesn't exist. 
This PR will fix by ignoring error while filtering logs by block hash.
=> fix: ignore block filter error for bor logs

consensus/bor/bor.go
Was going through consensus and it seems this method not called at all (not sure if you all using for the magic RPC usage)
=> GetPendingStateProposals not called

Dockerfile
In order to debug and navigate the file system within Bor while working in a docker container having bash will be useful. This addition will come in handy if people decide to orchestration their containers in clusters as well.
I faced the issue of not being able to peer into my Bor instance when it was containerized in a Monk.io cluster. This made it difficult to debug and run common commands such as sudo service bor restart
1. docker build -t dockerfile --target builder .
2. Run docker image to start container 
3. docker exec -it <container-name> /bin/bash
=> Added bash to docker container

Dockerfile
The Dockerfile for release using Alpine is in the included Dockerfile.release and this one was not used for release so doesn't make sense to have it using multistage nor Alpine.
=> Adapt Dockerfile for development

command/server/config.go, command/server/flags.go, command/server/server.go
- Adds service name in config and flags.
- Sets `os.Hostname()` to default
- Used in OpenCollector Config
- [Linear](https://linear.app/matic/issue/POS-68/add-a-new-name-field-in-bor)
=> added service name in config and flags

command/server/config.go
The default syncmode in the new CLI was changed from fast to full.
=> Changed syncmode from fast to full

.github/workflows/dockerimage.yml, .goreleaser.yml, Dockerfile.classic
This will recover the classic maticnetwork build in parallel with the new images so the community can test both images.
Also fix the new build manifest.
=> Build with the previous Dockerfile

.goreleaser.yml
This will create a static build using Go native networking stack.
Checked and it works stable for all archs and distros.
=> Build using netgo tag

eth/filters/filter_system_test.go
The bor/eth/filters folder lights up red with error due to a function call with less arguments. A borLogs additional field had been added previously  to the function. This PR reflects the same changes in the testcase with ` borLogs bool = true ` also passed while calling the function.
=> Removed errors in filter_system_test.go

Makefile
Reviewer @vcastellm
Fixes https://github.com/maticnetwork/bor/issues/272
Reorders such that bor is the first and therefore default target.
`make` builds bor
=> Reorder Makefile

cmd/geth/config.go, cmd/utils/flags.go
* Polygon does not use DNS discovery so remove the cargo-culted init call
* Default sync should be `full`
=> Do not attempt DNS discovery and change default sync flag

eth/gasprice/gasprice.go
Right now, whenever you do `eth.gasPrice` it will return the gas price estimate that will be capped at 500 Gwei. In reality, the gas price required to broadcast transactions is somewhere around 600-700 Gwei, but the node is returning 500 Gwei just because it has inherited the go-ethereum's gas price limiter.
=> Bump maximum Gas Price Oracle gas price to 5000 Gwei

Makefile, core/state_processor_test.go, eth/catalyst/api_test.go, eth/ethconfig/config.go, ethclient/ethclient_test.go, ethclient/gethclient/gethclient_test.go, mobile/android_test.go, params/config.go
The test _**https://github.com/maticnetwork/bor/blob/f3d6620eccb0c21225312de59f49ea83a66996c3/core/blockchain_test.go#L1162**_ fails.
This PR will fix this.
=> fix for TestReorgSideEvent

internal/cli/server/chains/developer.go, internal/cli/server/config.go, internal/cli/server/config_test.go, internal/cli/server/flags.go, internal/cli/server/server.go, internal/cli/server/server_test.go
This PR enables the developer mode for the new cli.
It introduces 2 flags, `--dev` and `--dev.period` for testing purpose by starting a mining node with dummy account. 
Linear: [POS 151: Run new cli in dev mode](https://linear.app/matic/issue/POS-151/run-new-cli-in-dev-mode)
=> Enable developer mode for new cli

docs/README.md, docs/cli/server.md, internal/cli/server/config.go, internal/cli/server/flags.go, internal/cli/server/server.go
This PR splits the jsonrpc module config into HTTP and WS modules.
=> Split modules for cli

.goreleaser.yml, Makefile, README.md, builder/files/bor.service
Build the new CLI in makefile and release pipeline.
=> Build and run the new CLI

internal/cli/server/config.go
This PR starts the http RPC server by default and also adds "eth" as default namespace.
=> Update default cli config

cmd/geth/consolecmd.go
The default ipc file is `dor.ipc`, but attach command using `geth.ipc`.
=> Fix default attach endpoint

cmd/utils/flags.go, docs/cli/server.md, internal/cli/server/flags.go
fix: modify the comment of txlookuplimit.
The comment of the txlookuplimit show as "Number of recent blocks to maintain transactions index for (default = about one year, 0 = entire chain)". It is correct for the Eth, but for bor, the default time is about 56 days.
=> fix: modify the comment of txlookuplimit

ethclient/ethclient.go
When i use ethclient to call BlockByHash or BlockByNumber at specify tx will get `server returned non-empty transaction list but block header indicates no transactions ` error,  like https://mumbai.polygonscan.com/block/17442944. That because if block only exist plasma deposit tx transaction will trigger this error. So if the block is legal, i think this check can be deleted.
=> fix: delete check empty tx root hash

internal/ethapi/api.go
https://github.com/maticnetwork/bor/pull/164/ when block has bor tx, all `transactionHash` as same
=> fix api GetTransactionReceiptsByBlock bug

builder/files/bor.service, internal/cli/server/server.go
Prometheus metrics was not working for three reasons: 
1. path was set to `/metric`
2. we need to use `Handler` instead of `HandleFunc`. Also see the same fix in v3 https://github.com/maticnetwork/v3/pull/52
3. bor.service did not enable metrics and prometheus's address
This commit fixes these problems.
=> Fix prometheus path and add prometheus to bor.service

internal/cli/server/config.go, internal/cli/server/config_test.go, internal/cli/server/testdata/password.txt
Currently in v0.3.0, validator couldn't mine new blocks, because the mining account is locked even when passed to "-unlock" flag. This commit will respect the functionality of flags "-unlock", "-password", and "-allow-insecure-unlock".
=> Implement and enable 'unlock' flag

internal/cli/server/config.go, internal/cli/server/config_test.go, internal/cli/server/server.go
This PR fixes error in the function definition of buildEth function in the new-cli server, introduced due to modifications in https://github.com/maticnetwork/bor/pull/394.
=> internal/cli/server: fixes in function definition

docs/cli/bootnode.md, docs/cli/server.md, internal/cli/server/config.go, internal/cli/server/config_test.go, internal/cli/server/flags.go, internal/cli/server/testdata/simple.hcl, internal/cli/server/testdata/simple.json
Rename legacy flag "whitelist" to new flag "requiredblocks" introduced in new geth cli.
=> Rename whitelist to requiredblocks

Dockerfile, consensus/bor/bor.go
* `make bor-all` will stop working in v0.3.0, changing the target to `bor` instead.
* Also fix a minor bug in logger.
=> Fix default Dockerfile for new CLI

internal/ethapi/transaction_args.go
While running bor `v0.2.14` I've realised that periodic annoying warnings occur in the logs:
```
Nov 12 08:44:29 eris bor[1278821]: WARN [11-12|08:44:29.032] Caller gas above allowance, capping      requested=9,223,372,036,854,775,807 cap=50,000,000
```
It's happening each ~5 minutes and it disrupts the logs and leaves a mess. I started investigating and found out that the message comes from here:
https://github.com/maticnetwork/bor/blob/783f93b1d7ef5e10fcca5a59399ad8b397368e96/internal/ethapi/transaction_args.go#L195
Further, I did a stack trace dump and found two cases that trigger the WARN:
```
runtime/debug.PrintStack()
runtime/debug/stack.go:16 +0x19
github.com/ethereum/go-ethereum/internal/ethapi.(*TransactionArgs).ToMessage(0xc00d3cedf8, 0x2faf080, 0xc06da5bac0) …
```
=> avoid capping warnings for gas set by internal system transactions

.github/workflows/ci.yml
Added reproducible build test to CI
https://linear.app/matic/issue/POS-392/reproducible-builds
=> Added reproducible build test to CI

docs/cli/server.md, internal/cli/flagset/flagset.go, internal/cli/flagset/flagset_test.go, internal/cli/server/config.go, internal/cli/server/config_test.go, internal/cli/server/flags.go, internal/cli/server/server.go
This PR does the following things:
1. Changes the following flags:
```
name -> identity
no-snapshot -> snapshot=False / snapshot=True
http.modules -> http.api
ws.modules -> ws.api
```
2. Fixes the bug where items are appended to the SliceString instead of overwriting it.
3. Adds a `Default` field to the `SliceStringFlag`.
4. Adds separate flags for `corsdomain` and `vhosts` for `http, ws, and graphql`.
```
http.corsdomain
http.vhosts
ws.corsdomain
ws.vhosts
graphql.corsdomain
graphql.vhosts
```
[POS-602](https://polygon.atlassian.net/browse/POS-602?atlOrigin=eyJpIjoiMzJjZDE1MjgwY2ViNDUyMGFjZGY5ZWUwMjQyZTk3N2IiLCJwIjoiaiJ9)
=> Change diverged flags back to Geth's convention (POS-602)

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md
This PR updates the github issue templates for bug, feature and question category. 
Checkout these files for preview: [Bug](https://github.com/maticnetwork/bor/blob/manav/POS-628-update-issue-template/.github/ISSUE_TEMPLATE/bug.md), [Feature](https://github.com/maticnetwork/bor/blob/manav/POS-628-update-issue-template/.github/ISSUE_TEMPLATE/feature.md) and [Question](https://github.com/maticnetwork/bor/blob/manav/POS-628-update-issue-template/.github/ISSUE_TEMPLATE/question.md). 
Jira: [POS 628 - Update github issue templates](https://polygon.atlassian.net/browse/POS-628)
=> github: add new issue templates

consensus/bor/bor_test.go, consensus/bor/heimdall/client_test.go
This PR adds a setup for using mock heimdall rest-server for testing various components of bor heimdall interaction. It creates a simple http-server with a mock handler for fetching checkpoints (for now), which can be updated throughout to the test case for simulating different scenarios. Moreover, additional handlers for different routes (span, state-sync, etc) can be added as per requirement. 
It tests timeout and cancellations in the heimdall client's `FetchWithRetry` function using timeout based context (added in https://github.com/maticnetwork/bor/pull/445)
Some of the cases tests are as follows: 
1. Handling delay in response from server causing error due to context timeout.
2. Handling cancellation of context
3. Handling user interrupt (leading to shutting of heimdall client). …
=> consensus/bor/heimdall: add mock heimdall rest-server, tests for timeout and cancellation

consensus/bor/snapshot.go, consensus/bor/valset/validator_set.go
The validator set json loaded from database will have an empty map. This change will recompute the validator map based on validator set.
=> Fix "Signer 0x... is not a part of the producer set at block xxxx"

core/blockstm/executor.go, core/blockstm/mvhashmap.go, core/blockstm/status.go, core/blockstm/txio.go, core/parallel_state_processor.go, core/state/journal.go, core/state/statedb.go, core/state/statedb_test.go, core/state_transition.go, go.mod, go.sum
The implementation of MVHashMap slightly differs from the original implementation by storing an instance of statedb, instead of the actual data bytes, as the value of a key in the map.
=> Create MVHashMap and use it in StateDB

Makefile
This PR adds a command to copy bor binary from `./build/bin/bor` to go bin.
=> Makefile: add copy bor binary to go bin command

eth/backend.go, internal/ethapi/api.go, tests/bor/bor_api_test.go, tests/bor/bor_filter_test.go
- If a block has both normal and bor transactions, getTransactionReceiptsByBlock returns receipts where all the receipts have the same txn hash( = state-sync txHash )
- The getTransactionReceiptsByBlock bug.
- The testcase covering getTransactionReceiptsByBlock.
The link to the issue is [here](https://polygon.atlassian.net/browse/POS-695?atlOrigin=eyJpIjoiMWQ5YmU3Y2I3ZWIyNDk4MGFmZjg3OTNkZDhiZGVlMzIiLCJwIjoiaiJ9).
=> Fix getTransactionReceiptsByBlock and TestGetTransactionReceiptsByBlock

eth/api.go, eth/tracers/api_bor.go, internal/ethapi/api.go, tests/bor/bor_api_test.go
In this PR:
- Fixed issue #369 .
- Added a testcase around the rpc call GetTransactionByBlockNumberAndIndex.
=> Fixed GetTransactionByBlockNumberAndIndex and added testcase around it.

cmd/geth/config.go, go.mod, go.sum, internal/cli/dumpconfig.go, internal/cli/server/config.go, internal/cli/server/config_legacy_test.go, internal/cli/server/testdata/test.toml
This PR,
- Replaced the `naoina/toml` package in `dumpconfig` with `BurntSushi/toml` package.
- Updated the toml name tags for the raw field types in the config structure.
- Updated/modified tests accordingly.
- Replaced the `naoina/toml` package in `cmd/geth/config.go` with `BurntSushi/toml` package.
[Jira Task Link](https://polygon.atlassian.net/browse/POS-687)
=> internal/cli, cmd/geth: replaced package naoina/toml with BurntSushi/toml and updated config name-tags

docs/cli/README.md, docs/cli/removedb.md, internal/cli/command.go, internal/cli/removedb.go, internal/cli/server/config.go
This PR adds support for removedb in the new-cli with similar functionality as in the old cli. 
It can be used as `bor removedb <datadir>` and is responsible to clear the blockchain and state databases. 
Note: It assumes that the `ancient` db lies inside the `chaindata` folder in datadir as we don't have access to the `DatabaseFreezer` path in the code. 
Jira - [POS-699: Support removedb in new-cli](https://polygon.atlassian.net/browse/POS-699)
=> internal/cli: add support for removedb

consensus/bor/heimdallgrpc/state_sync.go
This change should fix the issue where we might end up processing partial number of event records in case of an error in gRPC client - server streaming.
It will only return records when there is an EOF from server side, Which means all the records are processed, If there is any other error than EOF, It should return the error and no records (nil).
Reference : https://grpc.io/docs/languages/go/basics/#client-side-streaming-rpc
https://polygon.atlassian.net/browse/POS-718
=> Fix EOF error in gRPC state-sync

builder/files/config.toml
Added all fields and commented those which are not used.
=> builder/files: updated config.toml

cmd/utils/flags.go, eth/handler.go, eth/sync.go
We've seen a couple of scenarios where some of our internal nodes have migrated to snap sync mode. Until we make it working fully, this PR will prevent that from happening.
It adds a preventive layer in the cli (old one) so that it's not enabled through flag and also handles cases where is migrates to snap sync.
=> eth, cli: prevent snap sync mode migration - v0.2.x

cmd/utils/flags.go, eth/handler.go, eth/sync.go, internal/cli/server/config.go
We've seen a couple of scenarios where some of our internal nodes have migrated to snap sync mode. Until we make it working fully, this PR will prevent that from happening. 
It adds a preventive layer in the cli (old and new both) so that it's not enabled through flag and also handles cases where is migrates to snap sync.
=> eth, cli: prevent snap sync mode migration - v0.3.x

eth/handler.go
This PR fixes a bug in checking blocks (and hash) set using the `--requiredblocks` flag in the old cli. 
Reference: https://github.com/ethereum/go-ethereum/pull/24817
Jira - [[v0.2.16 and v0.3.0] Required block mismatch when whitelist blocks are provided](https://polygon.atlassian.net/browse/POS-726)
=> eth: fix whitelist/requiredblocks regression - v0.2.x

eth/handler.go
This PR fixes a bug in checking blocks (and hash) set using the `--requiredblocks` flag in the new cli. 
Reference: https://github.com/ethereum/go-ethereum/pull/24817
Jira - [[v0.2.16 and v0.3.0] Required block mismatch when whitelist blocks are provided](https://polygon.atlassian.net/browse/POS-726)
=> eth: fix whitelist/requiredblocks regression - v0.3.x

core/parallel_state_processor.go, core/state/statedb.go, core/state_transition.go, eth/tracers/api.go, eth/tracers/api_test.go
[Jira Task: POS-573](https://polygon.atlassian.net/browse/POS-573)
=> Dump IO Usage

internal/cli/server/config.go, internal/cli/server/config_legacy_test.go
Prior to this PR, 
Bor client running on ^v0.3.0 were setting 30Gwei  as default txpool.pricelimit which was not suitable for mumbai testnet. 
In this PR, the bor client will set 1 wei as default txpool.pricelimit.
=> Changing default txpool pricelimit to 1

consensus/bor/bor.go
This PR removes the log which was added in the `snapshot()` function in bor consensus added to check the ideal capacity for the slice.
=> consensus/bor: remove snapshot found log in bor consensus

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, eth/backend.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, eth/handler.go, internal/cli/server/config.go
The last PR (https://github.com/maticnetwork/bor/pull/497) already has the regression fix for the `eth.requiredblocks` to work correctly. It's also good to include other name changes which modifies the flag usage from `peer.requiredblocks` to `eth.requiredblocks` and corresponding variables. 
Reference: https://github.com/ethereum/go-ethereum/pull/24817
=> cmd: rename requiredblocks flag

ethclient/ethclient.go, ethclient/gethclient/gethclient.go, rpc/types.go
This PR adds new block type for "finalized and "safe" blocks to honour the post-merge API modifications. 
The purpose behind this change is to consume this client in heimdall for L1 communication i.e. ethereum mainnet and goerli test network which are already following these notions. 
Reference implementation from geth: https://github.com/ethereum/go-ethereum/pull/24282, https://github.com/ethereum/go-ethereum/pull/25165, https://github.com/ethereum/go-ethereum/pull/25580. 
NOTE: This by no means adds/serves "finalized" or "safe" blocks from bor.
=> rpc, ethclient: cater 'finalized' and 'safe' blocks in ethclient

ethclient/ethclient.go, ethclient/gethclient/gethclient.go, rpc/types.go
This PR cherry picks commits from https://github.com/maticnetwork/bor/pull/517 PR which was done for v0.2.18-candidate. 
-----
This PR adds new block type for "finalized and "safe" blocks to honour the post-merge API modifications.
The purpose behind this change is to consume this client in heimdall for L1 communication i.e. ethereum mainnet and goerli test network which are already following these notions.
Reference implementation from geth: https://github.com/ethereum/go-ethereum/pull/24282, https://github.com/ethereum/go-ethereum/pull/25165, https://github.com/ethereum/go-ethereum/pull/25580.
NOTE: This by no means adds/serves "finalized" or "safe" blocks from bor.
=> rpc, ethclient: cater 'finalized' and 'safe' blocks in ethclient (v0.3.x)

integration-tests/smoke_test.sh
Adding more support for Matic-CLI.The integration tests will not give false positives in case default validator balance in Matic-CLI is increased.
=> chg : generalised state-sync integration test

core/blockstm/dag.go
We only used to sort the roots, we should also modify the rootIds in the same order.
=> Fixed a small bug in the Report function

builder/files/config.toml, internal/cli/server/config.go, internal/cli/server/config_legacy_test.go, internal/cli/server/server.go, internal/cli/server/testdata/test.toml, scripts/getconfig.go
This PR achieves the following things
1. When the flag `nodiscover` was enabled in the old-cli, the node would not discover other peers but still connected to static and trusted peers if required, which was much convenient for our validator and sentry architecture. But, in the new-cli, when we set this flag, we also used to set `maxpeers` to 0. This would not allow the node to connect to any static peers. Ideally, we've suggested people to use [this](https://github.com/maticnetwork/launch/blob/master/mainnet-v1/sentry/validator/bor/start.sh#L39) setting of flags (`nodiscover` along with `maxpeers=0`). Now, we can either get rid of this flag and keep the same behaviour in client as it is now by not translating it the new toml file using @pratikpatil024's migration script or we can keep the …
=> internal/cli/server: fix flag behaviour

core/state_transition.go, tests/block_test.go, tests/init.go, tests/state_test.go
This PR un-skips a geth integration test and also fixes a minor bug encountered while running the tests. Initially, this PR was meant to trigger CI by "un-skipping"  failing integration tests  and verify whether these are related to Bor's implementation. 
Ref: https://polygon.atlassian.net/browse/POS-618
=>  Failing geth integration tests

scripts/getconfig.sh
This PR makes some modifications in the getconfig script which is used to generate the toml config file according to the new-cli from an old (v0.2.x) start.sh to make it executable on Mac and Linux machines. 
We've tried to make the solution simpler using some methods but that didn't work out. So, as of now, the current solution just includes if else statements at places to run commands depending on the current OS. 
[Reference Issue](https://stackoverflow.com/questions/43171648/sed-gives-sed-cant-read-no-such-file-or-directory)
=> scripts: make config creation script independent of OS

builder/files/config.toml, docs/cli/removedb.md, docs/cli/server.md, internal/cli/server/config.go, internal/cli/server/flags.go, scripts/getconfig.go
This PR adds support for `bor.logs` boolean flag in the new-cli. It also updates relevant places where it needs to be used. 
All the changes have been tested on a devnet.
=> internal/cli: add support for bor.logs flag in new-cli

core/blockstm/dag.go, core/blockstm/executor.go, core/blockstm/executor_test.go, core/parallel_state_processor.go
Calculate longest execution path based on the time each transaction spent .
Sample report output of alternating tx test:
```
INFO [10-04|17:03:21.538] Executing block                          numTx=200 numRead=20 numWrite=20 numNonIO=100
DEBUG[10-04|17:03:21.581] blockstm exec summary                    execs=200 success=200 aborts=0 validations=200 failures=0 #tasks/#execs=100.00%
Longest execution path:
(100) 0->2->4->6->8->10->12->14->16->18->20->22->24->26->28->30->32->34->36->38->40->42->44->46->48->50->52->54->56->58->60->62->64->66->68->70->72->74->76->78->80->82->84->86->88->90->92->94->96->98->100->102->104->106->108->110->112->114->116->118->120->122->124->126->128->130->132->134->136->138->140->142->144->146->148->150->152->154->156->158->160->162->164->166->168->170->172->174-> …
```
=> Add ability to calculate the longest execution path in a block

internal/cli/server/server.go, metrics/metrics.go
The metrics package uses global variables to enable metrics collection (with the flag `--metrics` and `--metrics.expensive`). As we're moving towards a toml config based approach, we found out that the values of these 2 parameters from toml file weren't being honoured in some cases. On further investigation we found out that due to the call to `init()` (in metrics/metrics.go), OS arguments were being read and metrics were being set based on those arguments. 
Now, there are some metrics which needs to be registered as soon the bor process starts. We were setting these global values but at much later point in the code when we're done setting up the node related processes which caused all the metric (meters, counters, gauges, etc) registrations to fail and hence leading to 0 values in …
=> metrics: handle values from config file

cmd/geth/config.go, docs/README.md, docs/config.md, internal/cli/server/config.go, scripts/getconfig.sh
Reference for this [commit](https://github.com/maticnetwork/bor/pull/555/commits/70cc54425847ca5c1707b9cb4cd01a6d424a64d0): https://askubuntu.com/questions/180873/shopt-works-in-command-line-not-found-when-run-in-a-script
=> Changed default value of maxpeers from 200 to 50,  update docs

consensus/bor/snapshot_test.go, core/forkchoice.go, go.mod, go.sum
In this PR, we start to use https://github.com/maticnetwork/crand instead of https://github.com/JekaMas/crand .
=> chg : use https://github.com/maticnetwork/crand instead of JekaMas/crand

builder/files/config.toml, core/blockchain.go, core/blockchain_test.go, core/tests/blockchain_sethead_test.go, eth/backend.go, eth/ethconfig/config.go, internal/cli/server/config.go, internal/cli/server/flags.go, les/handler_test.go, les/peer.go, les/server_requests.go, les/test_helper.go
In this PR we introduced a new flag `cache.triesinmemory` ( default : 128 ). With this change, a user can modify the number of block states ( tries ) to be stored in the memory.
=> Make TriesInMemory configurable through CLI and toml config

consensus/bor/statefull/processor.go, core/vm/interface.go, eth/tracers/api.go, eth/tracers/api_bor.go, eth/tracers/api_test.go
Because state sync transaction is added by bor consensus, it will not be included in `debug_traceByBlockNumber` and `debug_tranceByBlockHash`. The problem seems to be that block.Transactions() doesn’t contain state sync transaction.
In this PR, tracing can be possible on state-sync transactions as well. All the debug_trace functions will contain the traces of state-sync transactions, if present.
=> Add state sync transaction to debug_trace functions.

consensus/ethash/sealer_test.go
In this PR, we are fixing the indeterministic behaviour of TestRemoteMultiNotifyFull which caused failure of PRs in the CI. 
The error faced is : 
`sealer.go:394: WARN [11-04|16:45:09.256] Failed to notify remote miner            err="Post \"http://127.0.0.1:50643/\": context canceled"`
=> fix : TestRemoteMultiNotifyFull

eth/filters/api.go
In this PR, we add state-sync logs configurable using `--bor.logs` flag to the `GetFilterLogs` function, to also get state-sync transaction logs in the custom filters.
=> add : bor.logs in custom GetFilterLogs

Dockerfile, Dockerfile.alltools, Dockerfile.release
This PR updates the bor working directory to /var/lib/bor and runs the docker container as a non-root user (bor) as part of the v0.3.0 release. Same code changes as #591 but for the QA branch.
=> Docker v0.3.0 release for QA

Dockerfile, Dockerfile.release
Reverts use of `bor` user in docker containers, reverting to previously used `root` user due to hard-coded file paths used in matic-cli
=> Docker User

builder/files/bor.service, internal/cli/server/server.go, metrics/metrics.go, packaging/templates/systemd/bor.service
The `init()` function in metrics used to read the config file provided by the user during start up and abstract the `metrics` and `metrics.expensive` flags. The case where the config file is provided using an "=" separated value (e.g. config=path) was breaking as it was considering the flag=value as the flag name itself. This PR fixes it. It also updates the bor.service files to not use that convention as a space separated key value pair is an ideal format. 
- x ] I have tested this code manually on mumbai
=> metrics: handle equal to separated config flag

scripts/getconfig.go, scripts/getconfig.sh
This PR fixed an issue with the conversion script's static-nodes part (`start.sh` to `config.toml`) by making it OS-independent.
=> fixed static-nodes related buf (os independent)

builder/files/config.toml, internal/cli/server/config.go, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml
This PR updates the default flags in the toml based config files. The defaults present in the code are kept as similar to geth. The config files for mumbai and mainnet are updated. The new values are as below
||miner.gaslimit|miner.gasprice|txpool.gaslimit|gpo.ignoreprice|
|---|---|---|---|---|
|mainnet|30M|30 Gwei|30 Gwei|30 Gwei|
|mumbai|30M|1 Gwei|1 wei|2 wei|
Additionally, this PR also changes the cache override mechanism. Instead it keeps geth's default values in code (which are also same as mumbai - 1024) and the mainnet config files are updated with a mainnet suitable value (which is 4096).
=> Update default flags

metrics/metrics.go
This PR handles nil telemetry config case (which occurs when an unknown toml file is being passed in config flag).
=> metrics: handle nil telemetry check

.github/workflows/release.yml
Goreleaser-cross v1.19.x dropped support for authenticating to Docker Hub using environment variables. This PR uses the Docker Login GitHub action to authenticate for pushing images
Untested. Unable to test without building the release. Implementation based on review of changes in goreleaser-cross commit history as seen [here](https://github.com/goreleaser/goreleaser-cross/compare/v1.19.2...v1.19.3)
=> update Docker login for goreleaser-cross v1.19

Makefile
In gorelease-cross 1.19+, dockerhub authentication will require docker logion action followed by mounting docker config file. See https://github.com/goreleaser/goreleaser-cross#github-actions. Tested in personal test account: https://hub.docker.com/r/jerrycpoly/bor-test/tags.
=> Fix docker publish authentication issue

.github/workflows/release.yml
This reverts commit 4d19cf5342a439d98cca21b03c63a0bc075769cf. As we are still using v1.18.1 for goreleaser-cross for v0.3.0, the docker login method shouldn't be changed.
=> Revert "update Docker login for goreleaser-cross v1.19"

internal/ethapi/api.go
Reverts https://github.com/maticnetwork/bor/pull/435
=> Revert "Adding correct miner address on API at the RPC level (POS-553)"

docs/README.md, docs/cli/bootnode.md, docs/cli/chain_sethead.md, docs/cli/debug_block.md, docs/cli/debug_pprof.md, docs/cli/peers_add.md, docs/cli/peers_list.md, docs/cli/peers_remove.md, docs/cli/peers_status.md, docs/cli/removedb.md, docs/cli/server.md, internal/cli/flagset/flagset.go, internal/cli/server/flags.go
This commit adds default values to CLI helper and docs. When the default value of a string flag, slice string flag, or map string flag is empty, its helper message won't show any default value.
Example server CLI helper output:
```bash
$ bor server -h
Usage: bor [options]
Run the Bor server.
Options:
-chain
Name of the chain to sync ('mumbai', 'mainnet') or path to a genesis file (default: mainnet)
-identity
Name/Identity of the node
-log-level
Set log level for the server (default: INFO)
-datadir
Path of the data directory to store information
-datadir.ancient
Data directory for ancient chain segments (default = inside chaindata)
-keystore
Path of the directory where keystores are located
-config
File for the config file
-syncmode
Blockchain sync mode (only "full" sync supported) …
```
=> Add default values to CLI helper and docs

eth/fetcher/tx_fetcher.go
I'm suggesting that the polygon team consider lowering the TxFetcher pingback threshold from 500ms to 100ms. This change would have a number of benefits for the network, including faster transaction propagation, improved communication between validators and sentry nodes, and reduced incentives for spamming transactions on the network. Lowering the threshold to 100ms would not significantly increase network load, and is already in use by many power users who care about receiving transactions quickly. This change would improve the overall performance and reliability of the polygon network.
In propagating transactions through the p2p network, a node will send the full transaction directly to a small number of their peers, but the transaction hash to the majority. The TxFetcher is responsible …
=> Reduce txArriveTimeout to 100ms

core/blockchain.go, core/forkchoice.go, core/forkchoice_test.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/whitelist/service.go, eth/downloader/whitelist/service_test.go, interfaces.go, params/version.go
With introduction of RFC35 (validating chains through checkpoints), a check was added when a future chain import was done to prevent import of very long chains (>256 blocks long) without any validation. As the function `InsertChain` is being called by downloader, this error floated till the top and was responsible to drop peers. Ideally we just want to reject the chain and do not want to drop peers when we're receiving a long chain (as this is quite frequent). Also, pre-RFC35, it would behave in the same way i.e. reject long chains (at some later point in time) but won't drop peers. 
This PR adds a new error type for such scenarios i.e. long imports for future chains. At the downloader level, the invalid chain error won't be floated at the top and hence it won't drop peers. It will still …
=> handle future chain import and skip peer drop

.github/matic-cli-config.yml, .github/workflows/ci.yml
This PR updates matic-cli branch used in CI integration tests to `master` and also makes subsequent modifications to `matic-cli-config.yml`
=> CI: Update matic-cli branch in integration tests

README.md
v0.3.3 won't build with go 1.18:
```
$ make bor
mkdir -p /home/matic/go/bin/
go build -o /home/matic/src/bor/build/bin/bor ./cmd/cli/main.go
log/handler_go14.go:9:6: swapHandler redeclared in this block
log/handler_go119.go:9:6: other declaration of swapHandler
log/handler_go14.go:13:23: swapHandler.Log redeclared in this block
log/handler_go119.go:13:23: other declaration of Log
log/handler_go14.go:17:23: swapHandler.Swap redeclared in this block
log/handler_go119.go:17:23: other declaration of Swap
log/handler_go14.go:21:23: swapHandler.Get redeclared in this block
log/handler_go119.go:21:23: other declaration of Get
log/handler_go119.go:10:17: undefined: atomic.Pointer
note: module requires Go 1.19
make: *** [Makefile:30: bor] Error 2
```
Updating go to 1.19 fixed this.
Thus, the …
=> update requirements in README

builder/files/config.toml, docs/cli/example_config.toml, internal/cli/server/config.go, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml
In this PR we resolve an issue of huge rewinds. `trieTimeout`/`trieTimeLimit` is responsible for the frequency of storing block state to the persistent db for a full node. It was set to 60 minutes which resulted in huge gap between states of blocks in the persistent memory. We have reduced this gap to 10 minutes which will increase the frequency of storing the block states to the persistent database.
=> chg : trieTimeout from 60 to 10 mins

internal/cli/server/config.go
In this PR, we fix the misconfiguration of `triesInMemory` flag. After this fix, a user can modify the number of block states ( tries ) to be stored in the memory.
=> internal/cli/server : fix : added triesInMemory in config

consensus/bor/bor.go, eth/filters/bor_api.go, internal/cli/debug_pprof.go
Due to a nil value in state sync slice, a filter receiving it's subscription panics. This PR fixes it.
Additional context:
The issue was because the slice which was to be returned was initialised with all empty state sync objects before even it was filled with data. Due to some cause (mostly a validation issue), if the execution loop breaks, it will return that half-filled slice which has some nil elements. Others (filter services in this case) assume that there can’t be a nil element and hence they panic on receiving one.
- In case link the …
=> fix nil state-sync issue, increase grpc limit

core/blockchain_reader.go, tests/bor/bor_test.go, tests/bor/helper.go
This PR adds some additional check for state sync transactions to validate the nil state-sync bug ([issue](https://github.com/maticnetwork/bor/issues/686) and [bug fix PR](https://github.com/maticnetwork/bor/pull/695)).
Please post additional comments in this section if you have them, otherwise …
=> core, tests/bor: add more tests for state-sync validation

docs/cli/debug_pprof.md, internal/cli/debug_pprof.go
This PR adds a new flag called `skiptrace` in the `bor debug pprof` subcommand. In the 3 profiles which gets generated by default, the `trace` profile is expensive and consumes too much size (for grpc) as compared to the `cpu` and `heap` profiles. Even though we have increased the GRPC limit, the process can become fast if we can skip it using a flag itself.  …
=> internal/cli: add `skiptrace` flag for profiling

builder/files/config.toml, docs/cli/example_config.toml, internal/cli/server/config.go, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml
Reverts changes in [this PR](https://github.com/maticnetwork/bor/pull/692) for release. 
=> revert "trieTimeout from 60 to 10 mins" change

eth/fetcher/tx_fetcher.go
This reverts commit 243d231fe45bc02f33678bb4f69e941167d7f466.
I'm part of the team at FastLane Labs who are building out an ecosystem friendly MEV protocol for Polygon. Currently, we are in open beta and have validators representing more than 20% of new block production onboard.
This PR reverts a recent commit that has made it into the current develop branch which significantly reduces the txArriveTimeout variable in the `eth/fetcher/tx_fetcher.go` file.
This change seems to have been committed straight into develop, rather than going through a PR so it's hard for us to understand the rationale behind it, but we'd be keen to discuss that here.
Reducing the txArriveTimeout value to from 500 ms to 100 ms seems likely to increase the amount of noise in the p2p layer of the network, and will …
=> Revert "Reduce txArriveTimeout to 100ms"

common/context.go, common/context_test.go, common/set/slice.go, eth/tracers/api.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go
=> Event based pprof

consensus/bor/bor.go, consensus/bor/valset/validator_set.go, eth/ethconfig/config.go, internal/cli/server/config.go, internal/cli/server/flags.go, miner/fake_miner.go
In this PR, we added `--bor.devfakeauthor` flag. Using this we can run bor as a validator without the requirement of initial validator-set or Heimdall. This flag must be used with `--bor.withoutheimdall`.
=> consensus/bor : add : devFakeAuthor flag

.github/workflows/security-ci.yml, .github/workflows/security-sonarqube-ci.yml
This PR moves `sonarqube` into its own security ci.
This is use to the fact that our current `sonarqube` version can only run on 1 branch, the default one (`develop` in this case).
Since we want to keep majority of the checks on the PR level, we’ll move `sonarqube` into a separate `yaml` until license will be extended to run on every PR.
=> dev: chg: POS-1215 move sonarqube to own ci

builder/files/config.toml, docs/cli/bootnode.md, docs/cli/example_config.toml, docs/cli/server.md, internal/cli/bootnode.go, internal/cli/server/command.go, internal/cli/server/config.go, internal/cli/server/flags.go, internal/cli/server/server.go, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml, scripts/getconfig.go
`--verbosity` supports these (`TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, and `CRIT`) 6 logging levels.
=> Added verbosity flag, supports log-level as well, but will remove that in future.

internal/ethapi/api.go
Block from `BlockByNumberOrHash` function can be nil, so we need to check.
Code is the same as here: https://github.com/maticnetwork/bor/blob/c46aae23daf0a1a172e08f97dcf2d7159e33eae5/internal/ethapi/api.go
Issue: https://github.com/maticnetwork/bor/issues/725
=> Check if block is nil to prevent panic

miner/worker.go
While tracing `block` object was used and this was done even before `err != nil` was checked. It can cause panic while accessing fields like `block.Hash()` if the block is nil during setting attributes in tracing. This PR accesses those fields from the `env` of mining instead of block to avoid panics and still derive the values. 
Please post additional comments …
=> miner: use env for tracing instead of block

internal/testlog/testlog.go, log/logger.go, log/root.go, miner/worker.go
In this PR, log level for "Committed new tx" was changed from Info to Debug.
=> chg : commit tx logs from info to debug

Makefile, internal/cli/version.go, params/version.go
- Version ( was already present )
- GitCommit
=> Add : commit details to bor version

core/error.go, core/tx_pool.go, params/protocol_params.go
This PR adds a check in transaction pool to discard transactions which has size more than the max code init size. Reference of geth's PR: https://github.com/ethereum/go-ethereum/pull/26504. 
Important Note: 
This is a partial fix to an [EIP](https://eips.ethereum.org/EIPS/eip-3860) which has already been implemented fully in geth (and other ethereum clients) but requires hard fork as it modifies the validation rules in state transition. Hence, at the moment we're only adding a check in transaction pool to reduce the possibility of attack. The plan is to co-ordinate and have these changes in the next hardfork either by manually doing the changes referencing the [original PR](https://github.com/ethereum/go-ethereum/pull/23847) or by pulling upstream geth changes.  
Please complete this …
=> core, params: add max code init size check in txpool

consensus/bor/bor.go
This PR checks if the current signer (of a node) is eligible for mining (i.e. existing in a validator set) very early in `consensus.Prepare()`. Earlier it used to perform this check in `consensus.Seal()` which is too late in our case. It seems suitable for a PoW based network where you're not supposed to check eligibility to mine a block and try mining it whatever the case. In our case, a node which is not in the validator set will try to produce a block (prepare header, pick transactions by performing sorting in txpool, execute them, add state-sync by interacting with heimdall) and then in the last step before signing, it will know that it's not authorized to produce this block (i.e. does not exist in the validator set). This seems very unoptimised as we're wasting resources on things …
=> consensus/bor: handle unauthorized signer in consensus.Prepare

core/blockchain.go, miner/worker.go
Add additional traces to write block and set head function
=> core, miner: add sub-spans for tracing

internal/web3ext/web3ext.go, node/api.go, p2p/server.go
In this PR, we are adding two new RPC methods to setMaxPeers and getMaxPeers of a node respectively.
With this change, maxPeers can be adjusted in runtime. This can be used to perform several chaotic tests.
=> Feat : SetMaxPeers

core/blockchain.go
This PR is a fix on top of https://github.com/maticnetwork/bor/pull/753 where a common trace context was used instead of internal made context. 
=> core: use internal context for sending traces

core/blockchain.go
In this PR, we add the functionality to dump the blocks data in `~/impossibleReorg-<TIME>.txt`. This will allow better observability to resolve impossible reorg issues in the future.
=> core: add : impossible reorg block dump

core/blockchain.go, internal/ethapi/api.go
The output of newRPCTransactionFromBlockIndex was incorrect and hence many of the dependant RPC calls were giving wrong results. It has been fixed in this PR. 
https://github.com/maticnetwork/bor/pull/729 raised against `qa` branch.
=> internal/ethapi :: Fix : newRPCTransactionFromBlockIndex

.github/workflows/ci.yml, .github/workflows/packager.yml, .github/workflows/release.yml, .golangci.yml, .travis.yml, Dockerfile.alltools, Makefile, build/ci.go, go.mod, p2p/dnsdisc/client_test.go, p2p/dnsdisc/tree_test.go
In this PR, we bump go version from `1.19` to `1.20.1`
=> bump : go version from 1.19 to 1.20.1

go.mod, go.sum
In this PR, we bumped the version of the dependency `github.com/Masterminds/goutils` to `v1.1.1`
=> bump dep : github.com/Masterminds/goutils to v1.1.1

consensus/bor/bor.go, consensus/bor/heimdall/span/spanner.go, tests/bor/bor_test.go, tests/bor/helper.go
Verify validator set against local contract on receiving an end-of-sprint block. Tested locally in a devnet.
=> Verify validator set against local contract on receiving an end-of-sprint block

core/tx_list.go, core/tx_pool.go, core/tx_pool_test.go, core/txpool2_test.go
This PR adds few additional checks in the transaction pool which are derived from a fix in geth and helps in prevention of DoS attacks. 
Referencing details from geth's [PR](https://github.com/ethereum/go-ethereum/pull/26648). 
> This PR adds two new rules to the transaction pool:
>     - A future transaction can not evict a pending transaction
>     - A transaction can not overspend funds of a sender
Please complete this section with the steps you performed if you ran manual tests for …
=> core/txpool: implement additional DoS defenses from geth

builder/files/config.toml, consensus/bor/bor.go, consensus/bor/valset/validator_set.go, core/tx_pool.go, core/tx_pool_test.go, core/types/transaction_signing.go, docs/cli/example_config.toml, docs/cli/server.md, eth/backend.go, eth/ethconfig/config.go, internal/cli/server/config.go, internal/cli/server/flags.go, internal/ethapi/api.go, miner/fake_miner.go, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml
This PR introduces `rpc.allow-unprotected-txs` flag to facilitate replaying of transactions from a different network to a shadow node (i.e a node producing blocks in isolation with the state of the network from which transactions are being relayed). 
Currently, this flag is only meant to be enabled if we are running a shadow node.
=> core,eth,internal/cli,internal/ethapi: add --rpc.allow-unprotected-txs flag to allow txs to get replayed (for shadow node) 

builder/files/config.toml, docs/cli/example_config.toml, docs/cli/server.md, internal/cli/dumpconfig.go, internal/cli/server/config.go, internal/cli/server/flags.go, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml
We will take this up when working on all the PRs with `MEV` labels.
Linking these two points ([first](https://github.com/maticnetwork/bor/commit/fcb722e4bf5bdda23d4c91da40ab95c9023a80c3#commitcomment-100665900), and [second](https://github.com/maticnetwork/bor/commit/fcb722e4bf5bdda23d4c91da40ab95c9023a80c3#commitcomment-100675141)) mentioned by @thogard785 in this [commit](https://github.com/maticnetwork/bor/commit/fcb722e4bf5bdda23d4c91da40ab95c9023a80c3).
=> Added support for miner.recommit flag

internal/ethapi/api.go
In this PR, while creating access list we default to rpc gas cap when gas limit isn't provided in the transaction args instead of re-estimating for every list.  See ethereum/go-ethereum#25467
=> internal/ethapi: set rpc gas cap as default gas limit when creating access list

consensus/bor/bor.go
This PR reverts changes made in #651 which made the node bail out early when it realised it's not part of the validator set in `consensus.Prepare`. As a result of this, the pending blocks were not getting updated since the flow broke off before the `worker.commit` phase .
=> consensus/bor: revert "handle unauthorized signer in consensus.Prepare"

core/tx_list.go, packaging/templates/package_scripts/control, packaging/templates/package_scripts/control.arm64, packaging/templates/package_scripts/control.profile.amd64, packaging/templates/package_scripts/control.profile.arm64, packaging/templates/package_scripts/control.validator, packaging/templates/package_scripts/control.validator.arm64, params/version.go
This PR cherry-picks https://github.com/maticnetwork/bor/pull/805 and https://github.com/maticnetwork/bor/pull/806 which improves locks on a map used by transaction pool. 
Thanks and shout out to @thogard785 for helping in identifying and fixing this issue. 
Quoting the description from #805 by @thogard785
> The filter method of txSortedMap is typically called by caller that holds the "m" RWLock object.
> 
> During reorgs, however, a Filter method of txList calls the filter method of txSortedMap but does not engage the lock.
> 
> This Filter method is called only by the txPool methods demoteUnexecutables and promoteExecutables, which are only called during reorgs (which explains the low frequency with which this crash occurs).
Please complete this section if any breaking changes have been …
=> core: improve locks in txpool

core/parallel_state_processor.go, core/types/block.go, miner/worker.go, miner/worker_test.go
In this PR, I removed the first 2 elements in the TxDependency structure: the Transaction index and flag informing about delaying the fee transfer.
=> Optimized the dependency metadata structure

core/blockchain.go, core/blockchain_test.go, core/chain_makers.go, core/parallel_state_processor.go, core/state_processor.go, core/types.go, eth/state_accessor.go
Allow process in state processor to be interrupted by caller
=> State processor interrupt

core/vm/interpreter.go, internal/cli/server/config.go, internal/cli/server/flags.go, miner/fake_miner.go, miner/miner.go, miner/test_backend.go, miner/worker.go
=> [WIP] core, miner, internal/cli : added interruptCommitFlag and cache

eth/fetcher/block_fetcher.go
`Synchronisation failed, retrying         peer=<PEER ID> err="shutting down"` 
The above spamming in logs is fixed in this PR.
This PR is replica of the fix in [go-ethereum](https://github.com/ethereum/go-ethereum/pull/24652) .
=> eth/fetcher: if peers never respond, drop them

miner/worker.go
In this PR, we remove interrupt commit flow from select case of txsCh. Earlier, due to this "interrupt commit logs" were spamming the bor logs.
=> rm : remove interruptctx from txsCh select case

miner/fake_miner.go, miner/test_backend.go, miner/worker.go, miner/worker_test.go
In this PR, we fix the go-routine leak identified in the code.
=> fix : go-routine leak in commitInterrupt channel

log/logger.go
The addition of 'LvlDiscard Lvl = -1' at beginning of const block in commit e699254142 caused the iota assigned values of LvlCrit through LvlTrace to change from 0 to 5 to 1 to 6.
As these enumerated values were used in command line argument parsing in cmd/geth/ (and possibly other commands), commit e699254142 caused `--verbosity 3` to be interpreted as WARN instead of INFO (and likewise for the other numeric verbosity values.)
This restores the original enumerated const values to LvlCrit through LvlTrace by moving LvlDiscard after all the iota assigned constants. Usage of auto-increment enumerations does not work the same way in golang as it does in C/C++ and its behaviour is detailed in the link below.
https://go.dev/ref/spec#Iota
=> Restore log level enumerated constants

builder/files/config.toml, docs/cli/example_config.toml, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml
In this PR, we add the `commitinterrupt` flag to the config toml files.
=> add : commitinterrupt flag to toml files

builder/files/config.toml, docs/cli/example_config.toml, docs/cli/server.md, internal/cli/server/config.go
In this PR, we change the default `OpenCollectorEndpoint` to `empty` string. Earlier, logs were getting spammed by `traces exporter is disconnected from the server 127.0.0.1:4317` error.
=> internal/cli/server :: chg : default OpenCollectorEndpoint to empty string

core/blockstm/mvhashmap.go
A reverted transaction, X, can incorrectly write to a slot, which might be read by another transaction, Y. If we skip checking states written by X, then Y might end up with reading the wrong value and we won't be able to detect this error.
Please post additional comments in this section if you have …
=> Disable reverted tx optimization in block-stm validation

metrics/prometheus/collector.go, metrics/prometheus/collector_test.go
Follow up PR to complete efforts from #881 as it did not produce the desired results. Digging in revealed that the metrics in question are registered as a [Timer](https://github.com/maticnetwork/bor/blob/develop/core/blockchain.go#L82), not as Summary. Timer metrics are not part of the defined [Prometheus metrics types](https://prometheus.io/docs/concepts/metric_types/). 
This PR updates the Timer metric type to format and display as a Prometheus Summary metric (which I think was the intended behavior all along), consistent with the changes introduced in #881. 
No breaking changes, all data previously presented by the metrics endpoint is still there. Formatting has been changed to follow Prometheus-type definitions, resulting in compatibility with the Open Telemetry Collector.
=> DEVOPS-829 format Timer as summary/histogram type

core/state_transition.go
There is no reason to make the bytes transformation and back to big int to assign a big int to another one.
The `Set` method should be used instead.
=> Use `big.Int#Set` instead of `big.Int#SetBytes` when possible

builder/files/genesis-mainnet-v1.json, internal/cli/server/chains/mainnet.go, params/config.go
Added [Indore block](https://polygonscan.com/block/countdown/44915456) and parallel universe for mainnet for the Indore Hard Fork.
This PR adds the Indore HF block number (state-sync bug) and also adds the parallel universe block (which enables parallel execution of transactions while verifying blocks).
Every mainnet node must update.
=> Added Indore block and parallel universe for mainnet

core/state_transition.go, core/txpool/txpool.go, eth/downloader/downloader_test.go, eth/protocols/eth/handler_test.go, eth/tracers/api_test.go, miner/test_backend.go
This WIP PR fixes a set of failing test cases in this [commit](https://github.com/maticnetwork/bor/commit/a25bc7794a6f0989979353c750164ddf6238e70a)
=> core,eth,miner: fix initial test cases

miner/worker.go
The `baseFee` can be `nil` in certain situations, the worker must not convert `baseFee` to `*big.Int` unless it was checked otherwise if such case happen, Go is going to panic:
```
goroutine 115 [running]:
math/big.(*Int).Bits(...)
/opt/homebrew/Cellar/go/1.20.4/libexec/src/math/big/int.go:105
github.com/holiman/uint256.(*Int).SetFromBig(0x14001297410?, 0x107714520?)
/Users/maoueh/go/pkg/mod/github.com/holiman/uint256@v1.2.0/conversion.go:102 +0x24
github.com/holiman/uint256.FromBig(...)
/Users/maoueh/go/pkg/mod/github.com/holiman/uint256@v1.2.0/conversion.go:50
github.com/ethereum/go-ethereum/common/math.FromBig(0x1073923e0?)
/Users/maoueh/work/sf/ethereum.chain/common/math/uint.go:20 +0x34
github.com/ethereum/go-ethereum/miner.(*worker).fillTransactions.func4({0x1400015c080?, …
```
=> Fix worker `nil` pointer exception because of `baseFee == nil`

core/blockstm/executor.go, core/blockstm/executor_test.go, core/parallel_state_processor.go
This will prevent data races when more than one parallel execution are running at the same time.
=> Move NumSpeculativeProcs from module variable to function parameter

core/blockchain.go, core/forkchoice.go, core/forkchoice_test.go, core/headerchain.go, eth/downloader/downloader.go, eth/downloader/downloader_test.go, eth/downloader/whitelist/checkpoint.go, eth/downloader/whitelist/finality.go, eth/downloader/whitelist/milestone.go, eth/downloader/whitelist/service.go, eth/downloader/whitelist/service_test.go, eth/handler_bor.go, interfaces.go
Error message was inconsistent with the error message being returned by HeimdallClient making error check in `fetchNoAckMilestoneByID` useless
=> Updates to Milestones Audit PR

graphql/graphql.go
Please, refer to https://github.com/ethereum/go-ethereum/pull/27873 
Executed scripts as per bb22944 Immunify report
=> graphql: dev: chg: avoid greedy allocation on graphql blocks call

metrics/prometheus/collector.go, metrics/prometheus/collector_test.go
With changes done in https://github.com/maticnetwork/bor/pull/881/ and https://github.com/maticnetwork/bor/pull/893/, the `count` field of a metric was added into summary and was calculated in wrong way. The tests didn't complain as they were updated in few places to cater to the new logic or the values according to the new logic vs old logic turned out to be same for the test case 
E.g. histogram count should be ideally 0 as no values are reported but it was changed to 6 which actually denotes the total percentile values reported. In case of timers, the values reported were 6 and the percentiles were also 6 so the test didn't catch this check. 
This PR updates (or actually reverts) the reporting of count metric. Instead of reporting count as `len(values)` where values are the total …
=> metrics/prometheus: fix count field of metric

RETESTBOR.md
This is a minor documentation change. While reviewing the `RETESTBOR.md` file I noticed that the section describing the testing config file was a bit hard to follow. I restructured it to hopefully be a bit easier to read.
=> fix: Improve RETESTBOR.md document formatting

builder/files/config.toml, docs/cli/example_config.toml, docs/cli/server.md, internal/cli/server/config.go, internal/cli/server/flags.go, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml
With recent changes in geth a new flag was introduced to select upon the database. We already have the required changes after upstream merge, I've just added the flag to select the database.
N.A
N.A
I've tested it locally and it works well.
[POS-1763](https://polygon.atlassian.net/browse/POS-1723)
=> internal/cli: add db.engine flag

ethclient/bor_ethclient.go
Bor is flexible enough to also reply to the call `eth_getRootHash` even though it belongs to `bor` namespace. Hence, the eth client used to call `eth_getRootHash` instead of `bor_getRootHash` and it's being used in heimdall for checkpoints. This works for bor and heimdall but causes issue in erigon because when heimdall asks an erigon node for the root hash, it responds with `method not available` error as this method lies in the `bor` namespace in erigon rpc. This PR fixes it by just calling the `bor` namespace instead of `eth` so that heimdall can also communicate with erigon. 
Will also raise a PR in heimdall to use this version of bor. 
In case this PR includes changes that must be applied only to …
=> ethclient: use `bor_getRootHash` instead of eth namespace

consensus/bor/contract/client.go, consensus/bor/statefull/processor.go
In this PR, we log the cases in which state-sync fails to commit a tx on the contract inner-call level.
=> add : statesync execution verbosity

packaging/templates/package_scripts/postrm
Fixing postrm to not remove service file and config.toml.
- [ x] Bugfix (non-breaking change that solves an issue)
=> Adding fix for postrm removing the config.toml and service file

consensus/bor/bor.go, core/txpool/list.go
=> log cleanup

eth/backend.go, miner/fake_miner.go, miner/miner.go, miner/test_backend.go, miner/worker.go, p2p/server.go, params/config.go
In this PR, we wait for a validator node to connect to atleast 1 peer before starting to produce blocks. This helps in stopping the validator to creating its own fork which might later result in the entire networking getting reorged to that fork. This PR tries to improve the stability of the network. 
This is only implemented to work on `mainnet` and `mumbai`. It will not work on devnets/testnets.
=> miner/worker :: add : start commit work only after connecting to peers

.github/workflows/ci.yml
This PR increases the timeout for smoke tests to 60 minutes in the CI workflow.
=> CI: Increase smoke test timeout

cmd/geth/chaincmd.go, cmd/geth/dao_test.go, cmd/utils/flags.go, core/bench_test.go, core/rawdb/database.go, docs/cli/server.md, eth/backend.go, eth/ethconfig/config.go, eth/filters/bench_test.go, eth/filters/filter_test.go, ethdb/leveldb/leveldb.go, internal/cli/server/config.go, internal/cli/server/flags.go, internal/cli/snapshot.go, les/client.go, les/server.go, node/node.go, node/node_test.go
I wired up CLI flags to allow configuring LevelDB table and total sizes:
- `--leveldb.compaction.table.size`, LevelDB SSTable file size factor in MiB (default: 2)
- `--leveldb.compaction.table.multiplier`, multiplier on LevelDB SSTable file size (default: 1)
- `--leveldb.compaction.total.size`, total size factor in MiB of LevelDB levels (default: 10)
- `--leveldb.compaction.total.multiplier`, multiplier on LevelDB total level size (default: 10)
N.B. that the default values for these configs are exactly the same as before this changset and so Bor behavior should not change unless these flags are deliberately overridden. Bor/Geth inherited the default values from [the `goleveldb`
defaults](https://github.com/syndtr/goleveldb/blob/126854af5e6d8295ef8e8bee3040dd8380ae72e8/leveldb/opt/options.g …
=> Add CLI flags to config LevelDB table/total sizes

core/txpool/txpool.go
Fixed `concurrent map read and map write` issue introduced during the upstream merge.
=> Fixed Panic - Added RLock on pool.pendingMu in validateTxBasics()

cmd/utils/flags.go
Fixing eth_getLogs for state-sync txns.
=> Use borLogs instead of default

README.md, internal/cli/bootnode.go
Enable prometheus in bootnode for monitoring purpose and provide cli options to change listening port.
=> Enable prometheus in bootnode

rpc/execution_pool.go, rpc/handler.go
All execution pools need to be closed properly. This fixes a potential goroutine leak caused by metric goutine created by each execution pool.
=> Stop execution pool in rpc handler

internal/cli/dumpconfig.go, internal/cli/flagset/flagset.go, internal/cli/flagset/flagset_test.go, internal/cli/server/command.go, internal/cli/server/command_test.go, internal/cli/server/config_legacy_test.go, internal/cli/server/flags.go, internal/cli/server/testdata/test.toml, scripts/getconfig.go
With the new-cli introduced in v0.3.0, there were 2 ways to set the configuration required to run bor. One can either do it via normal cli flags (args) or via a toml based config. Due to some restrictions, if the toml based config is provided, bor overwrites all the given cli flags (explicitly by the user) with those provided in toml config. 
An ideal behaviour should in any cli application should be that explicitly provided flags should take control no matter what value is provided in the toml based config. This PR implements that. Sufficient tests have been added and existing tests have been improved to cover all cases for all data types. 
The order of flag will now be as follows:
1. If set in cli args, use that value
2. If not set in cli args and set in config, use that value
3. If not …
=> internal/cli: add support to overwrite config.toml values via cli flags

internal/ethapi/api.go
In this PR, we fix the issue in which bor transaction was showing chainID `0x7fffffffffffffee`.  Bor transaction did not usually output a chainID but was recently introduced to do so with the upstream from go-ethereum ( below ). 
```
// if a legacy transaction has an EIP-155 chain id, include it explicitly
if id := tx.ChainId(); id.Sign() != 0 {
result.ChainID = (*hexutil.Big)(id)
}
```
=> fix : borTx chainID

trie/trie.go
Added more locks to fix concurrent map read and map write issues introduced during the upstream merge.
=> Added locks to the tracer

consensus/bor/heimdall/client.go, eth/backend.go, eth/handler_bor.go
When a new feature (like for the upcoming `Aalborg` hard fork) hasn't kicked in, the endpoints of heimdall will now return 503 (Service Unavailable) status code. This PR makes sure that bor handles that code separately and doesn't keep retying to fetch info. 
- In case link the PR here: https://github.com/maticnetwork/heimdall/pull/1073
=> eth, consensus/bor: handle 503 status code in heimdall client

internal/ethapi/api.go, internal/ethapi/bor_api.go
In #1021 , we fixed the borTx chainID for method `eth_getTransactionByHash`.  Some methods like `eth_getBlockByNumber` got missed. In this PR, we are fixing the rest of the methods that we identified to also send false borTx chainID.
=> fix : wrong chainID on rpc

.github/workflows/ci.yml, Makefile
This PR adds codecov for integration tests. It also adds coverage for combined cover reports from unit-tests and integration-tests.
=> Fix Codecov and add integration tests coverage

internal/cli/server/command_test.go, internal/cli/server/config.go, internal/cli/server/config_legacy_test.go, internal/cli/server/flags.go, internal/cli/server/testdata/test.toml
With the recent changes in new-cli to support overriding of config values by cli flags, due to the missing default value of the keystore flag, the flag library used empty string as the final value and the original value even if set get's ignored. This PR fixes it. 
Affects validators mostly as they're using keystore flag
=> internal/cli: set default value for keystore

eth/api.go, eth/api_backend.go, eth/filters/filter.go, internal/ethapi/bor_api.go
This PR includes a subset of changes from https://github.com/ethereum/go-ethereum/pull/27218 which checks for nil header, state and receipt values when node is syncing and calls to pending are made. 
Note that the rest of the changes in the PR will be pulled in routine upstream merge. Only the required fix is pulled. 
This PR also handles nil state or error in the `SendRawTransactionConditional` api.
=> eth: handle nil blocks and state when pending is not available

consensus/bor/bor.go, core/genesis.go, core/state_processor.go, eth/protocols/eth/handler_test.go
Makes withdrawals objects `nil`
=> bor: make withdrawal objects nil

core/types/tx_dynamic_fee.go
In this PR, we fix a typo in `core/types/tx_dynamic_fee.go`.
=> fix : typo in (tx *DynamicFeeTx) gasPriceU256()

core/vm/jump_table.go, packaging/templates/package_scripts/control, packaging/templates/package_scripts/control.arm64, packaging/templates/package_scripts/control.profile.amd64, packaging/templates/package_scripts/control.profile.arm64, packaging/templates/package_scripts/control.validator, packaging/templates/package_scripts/control.validator.arm64, params/version.go
=> rm : prevrandao

go.mod, go.sum, params/config.go
=> Bump deps for sec updates

core/blockchain.go, core/parallel_state_processor.go, core/vm/interpreter.go, eth/backend.go, miner/worker_test.go
=> Fix ParallelSpeculativeProcesses flag

core/txpool/legacypool/legacypool.go, core/txpool/validation.go, core/types/transaction_signing.go, eth/backend.go
Hot fix for checks missing for allowing shadowfork and relay to work
=> allow unprotected txns

internal/ethapi/api.go
`effectiveGasPrice` is missing in the **Receipt** of the **GetTransactionRecipetsByBlock** method.
Also, the initialization type of `log` is invalid.
Hi, I'm currently implementing a Polygon Indexer. I'm using bor client and I found an error in that method. I hope it's reflected quickly.
=> internal/ethapi: fix GetTransactionReceiptsByBlock method

internal/cli/server/config_legacy_test.go, internal/cli/server/testdata/default.toml
Added a unit test to check the default values of all the flags in config file
=> Added a unit test to check the default values of all the flags in config file

cmd/evm/testdata/3/readme.md, cmd/evm/testdata/4/readme.md, core/state/pruner/pruner.go, eth/backend.go, packaging/templates/package_scripts/control, packaging/templates/package_scripts/control.arm64, packaging/templates/package_scripts/control.profile.amd64, packaging/templates/package_scripts/control.profile.arm64, packaging/templates/package_scripts/control.validator, packaging/templates/package_scripts/control.validator.arm64, params/version.go
This PR fixes Pruning Bug introduced in v1.2.0
=> Pruning Bug Fix

internal/ethapi/api.go, internal/ethapi/api_test.go
In `GetTransactionReceiptsByBlock`, the value `from` is sometimes zero address. Therefore, I changed the code that creates the signer by referring to the code implemented in `GetTransactionReceipt`.
Looking at the code, only the signer of legacy transaction with type 0 is being made.
The block used as an example:
- blockNumber - 51178987
- rpc - eth_getTransactionReceiptsByBlock
- result (transactionHash, from, to)
```
0x8af449a3dc8214a3b3fea2bdaef6afd8857c326902b25f8254aa1df46d988e33 0x0000000000000000000000000000000000000000 0x91b431a541872d0b3c55f3381cb391d9347f1552
0x5d4e69d161ff90da3a67a303029574130159248b69c51cbe559d0230558fc1f9 0x0000000000000000000000000000000000000000 0xa3fb72cbf2e07dc1b34aea569ed40755fd978bd8
0x92f1b7e86b2ce03a01c1c0f7ca211843af96710666986b4eb743dcefcd7eec75 …
```
=> internal/ethapi: fix signer in GetTransactionReceiptsByBlock method

eth/bor_api_backend.go
Removed the check for milestoneID in the GetVoteOnHash() function, in present system there is an extra check which query the authenticity of the milestone being voted by querying the milestoneID from the Heimdall.
It seemed to be an extra check which extra call overhead and sometime also causing delay.
- [.] Bugfix (non-breaking change that solves an issue)
=> Removed the check for milestoneID in the GetVoteOnHash()

core/state/pruner/pruner.go, eth/backend.go, packaging/templates/package_scripts/control, packaging/templates/package_scripts/control.arm64, packaging/templates/package_scripts/control.profile.amd64, packaging/templates/package_scripts/control.profile.arm64, packaging/templates/package_scripts/control.validator, packaging/templates/package_scripts/control.validator.arm64, params/version.go
This PR contains bug fixes for geth upstream merge v1.12.2
- Pruning fix
=> Geth Merge v1.12.2 Hotfixes

consensus/bor/heimdall/client.go, consensus/bor/heimdall/client_test.go
As reported to the polygon team 2 months ago in the Ankr polygon slack, the current code prevents the use of a path with the heimdall url, this was fixed in erigon https://github.com/ledgerwatch/erigon/commit/a3a61701e2cee5b1302ddf2c02dbfcb291522c64 in response to my request by Mark Holt, and it seems this code was just copied from bor where it is incorrect too. This patch fixes that.
=> Update client.go to allow the use of paths with the heimdall url

.github/matic-cli-config.yml, integration-tests/bor_health.sh, integration-tests/smoke_test.sh
Update bor ipc path based on new director structure
=> integration-tests: update ipc path on ci tests

graphql/graphql.go, internal/ethapi/api.go
Hotfix for v1.2.2. This PR fixes the `CallWithState` call which happens during state-sync processing by passing correct state to lower functions.
Tested on internal devnode
=> internal/ethapi, graphql: fix call with state api

miner/worker.go
When `delayFlag` becomes `false`, `tempDeps` will be ignored, so there's no need to continue the loop.
=> break out of loop when `delayFlag` becomes `false`

core/blockstm/mvhashmap.go
Cherry-picks @zhiqiangxu's commits from #1120.
=> fix bug: should use Lock when mutating the flag

cmd/bootnode/main.go, internal/cli/bootnode.go
This fixes the bootnodes issue due to which the port mapping was getting done properly. Added a helper function to export the logic from bootnodes binary, this won't require any update on bootnodes flag function incase there is a change from upstream.
I tried connecting two nodes using the bootnode.
=> fix: bootnode

core/blockchain.go
This pull request resets the txlookup cache if chain reorg happens,  preventing them from remaining reachable. It addresses failures in the hive tests.
Cherry-picked [geth#28865](https://github.com/ethereum/go-ethereum/pull/28865).
=> core: reset tx lookup cache if necessary

core/blockchain.go, miner/worker.go
This PR adds debug logs for the ongoing sync issues
=> core, miner: add debug logs to track chain insertion

eth/downloader/downloader.go
Don't stop sync if remote peer is far away (1024 blocks for now)
=> eth/downloader: bypass peer validation if remote peer is far away

integration-tests/bor_health.sh, integration-tests/smoke_test.sh
Based on `matic-cli` [PR](https://github.com/maticnetwork/matic-cli/pull/225), this adapts the path accordingly also in `bor` integration tests
- In case link the PR here: https://github.com/maticnetwork/heimdall/pull/1139
- In case link the PR here: https://github.com/maticnetwork/matic-cli/pull/225
=> Fix path for `matic-cli` dockerized tests

.github/workflows/ci.yml, integration-tests/fund_ganache_accounts.sh
Often, the checkpoints submission during the `e2e tests` in the CI takes a very long time (35+ mins) due to lack of funds in ganache accounts (with `index > 0`), which ends up in checkpoints submission failure, and subsequent rotation until it's `accounts[0]` turn. 
This PR introduces a new script to fund the ganache accounts right before the `e2e tests`, to reduce the checkpoint submission time from 35+ mins to around 2 mins.
=> POS-2399: ganache bug workaround to reduce `smoke_test` time in CI

core/state/state_object.go
Added lock to `originStorage`, `pendingStorage` and `dirtyStorage` in `GetCommittedState()` function to fix `concurrent map writes`
=> fix: concurrent map writes

core/blockchain.go
This PR does 2 things:
- Removes tracing in writeBlockAndSetHead function: tracing isn't used anymore and this simplifies the code a lot
- Fixes a bug when the reorg function returns error (when we receive an error we update the status to NonStatTy but don't return at that point. Later the status is updated irrespective of the above error and may lead to wrong processing. This PR fixes that and returns from the function immediately). This change also matches with the upstream implementation of the same function.
- …
=> core: remove tracing and handle err in reorg call

accounts/abi/bind/util_test.go, eth/api_miner.go, miner/miner.go, miner/ordering.go, miner/ordering_test.go, miner/test_backend.go, miner/worker.go
* eth, miner: fix enforcing the minimum miner tip
* ethclient/simulated: fix failing test due the min tip change
* accounts/abi/bind: fix simulater gas tip issue
Cherry-picked https://github.com/ethereum/go-ethereum/pull/28933.
=> eth, miner: fix enforcing the minimum miner tip (#28933)

.golangci.yml, Makefile, core/txpool/legacypool/legacypool_test.go, rlp/unsafe.go
This PR does the following things
- Upgrade golangci-lint to latest version: v1.57.2 to eliminate few lint errors
- Fix few lint errors by referencing from upstream
Note that the lint will still fail on few crypto related packages. Those changes are already done in geth in https://github.com/ethereum/go-ethereum/pull/28946 but as it's not yet added to a stable release, I'll refrain it from fixing in this PR. It can be take care of during the next upstream merge.
Please complete this …
=> Update lintci and fix lints

consensus/bor/bor.go, consensus/bor/bor_test.go, core/txpool/legacypool/legacypool.go, core/txpool/validation.go, core/types/transaction_signing.go, eth/backend.go, eth/bor_api_backend.go, internal/cli/server/config_legacy_test.go, internal/cli/server/testdata/default.toml, params/config.go
Adds changes back from the reverted [PR#1124](https://github.com/maticnetwork/bor/pull/1124/)
Changes:
- Make hardfork naming consistent across all the blocks @anshalshukla 
- Enables unprotected txns @temaniarpit27
- Test default flags added via config @pratikspatil024 
- Fix balance update via blockalloc at HF @anshalshukla 
- Fix milestone getVoteOnHash @VAIBHAVJINDAL3012 
Please complete this section with the steps you performed if you ran manual tests for this functionality, …
=> Add: Changes reverted in PR#1124

core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool_test.go, docs/cli/example_config.toml, docs/cli/server.md, eth/backend.go, eth/catalyst/api_test.go, eth/gasprice/gasprice.go, internal/cli/server/config.go, internal/cli/server/config_test.go, internal/cli/server/testdata/default.toml, miner/miner.go, miner/worker_test.go, packaging/templates/testnet-amoy/archive/config.toml, packaging/templates/testnet-amoy/sentry/sentry/bor/config.toml, packaging/templates/testnet-amoy/sentry/validator/bor/config.toml, packaging/templates/testnet-amoy/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml, params/protocol_params.go
This PR enforces the params `txpool.pricelimit`, `miner.gasprice` and `gpo.ignoreprice` to be set to 30 gwei.
- Related erigon PR: https://github.com/ledgerwatch/erigon/pull/10119
=> core, eth, internal, miner, params: enforce 30gwei for gas related configs in bor

eth/tracers/api.go
`debug_traceBlockByHash` and `debug_traceBlockByNumber` may return incorrect result because there is a data race in code.
Data race may happen when tracing block that contains bor transaction, it may cause that a common transaction is treated as a bor transaction.
This PR tries to fix the issue.
No.
=> eth/tracers: avoid data race when tracing block with bor tx

internal/ethapi/api.go, tests/bor/bor_api_test.go
Fixes hashing of state sync transactions in RPC calls.
=> Fix state sync hash

eth/handler.go
A follow-up of [PR#1243](https://github.com/maticnetwork/bor/pull/1243)
=> eth: explicitly commented the code were bor could get into snap-sync mode 2.0

eth/handler.go, eth/protocols/eth/peer.go, internal/ethapi/api.go
The block is broadcasted to only Sqrt(peers) in geth. We observed that in case of validator-sentry architecture, the validator, sometime, might not receive a block which will force the validator to mine on his own, resulting in a reorg.
In this PR, we are making sure that the block will be broadcasted to all the static and trusted peers of a particular node. …
=> eth: broadcast block to static and trusted peers as well

eth/fetcher/block_fetcher.go
This PR updates few constants used in block fetcher to suit PoS block timings i.e. 2s as compared to ethereum which is 12s. 
Block fetcher handles downloading of block headers and bodies near the chain tip as it acts upon the block and block hash announcements. A constant `maxQueueDist` is used to queue the block announcements and it's value was initially set to 32. This means that it only stores the block announcements of last 32 blocks from the chain tip. 
While debugging the sync issues observed recently, we identified that old block announcements were dropped while newer ones were included. This used to stall the import as we would have some missing blocks in this case. It can only proceed in 2 cases. 
- Missing blocks are queried again -- as we've dropped the announcement way …
=> eth/fetcher: modify queue limits for improving sync near chain tip

cmd/devp2p/discv4cmd.go, cmd/devp2p/internal/v4test/framework.go, internal/testlog/testlog.go, node/api.go, p2p/dial.go, p2p/discover/common.go, p2p/discover/lookup.go, p2p/discover/metrics.go, p2p/discover/node.go, p2p/discover/table.go, p2p/discover/table_reval.go, p2p/discover/table_reval_test.go, p2p/discover/table_test.go, p2p/discover/table_util_test.go, p2p/discover/v4_lookup_test.go, p2p/discover/v4_udp.go, p2p/discover/v4_udp_test.go, p2p/discover/v4wire/v4wire.go, p2p/discover/v5_talk.go, p2p/discover/v5_udp.go, p2p/discover/v5_udp_test.go, p2p/enode/idscheme.go, p2p/enode/node.go, p2p/enode/node_test.go, p2p/enode/nodedb.go, p2p/enode/urlv4.go, p2p/enr/entries.go, p2p/server.go
cherry-pickd the following PRs from geth for peering issues
https://github.com/ethereum/go-ethereum/pull/29572
https://github.com/ethereum/go-ethereum/pull/29864
https://github.com/ethereum/go-ethereum/pull/29801
https://github.com/ethereum/go-ethereum/pull/29827
https://github.com/ethereum/go-ethereum/pull/29836
https://github.com/ethereum/go-ethereum/pull/29844
https://github.com/ethereum/go-ethereum/pull/29235
Please complete this section with the steps you performed if you ran …
=> p2p: cherry-pick commits from geth for peering issues

internal/cli/snapshot.go
The ancient pruner moves the required block data to a different ancient datadir and deletes the old one once the migration is completed. In cases when the user doesn't have delete permissions on the ancient datadir (if it's on a different mounted disk), the pruning fails. Although it can be recovered, it requires manual efforts. 
This PR checks if the user has delete permissions on the ancient datadir beforehand. 
Please complete this section with the steps you performed if you ran …
=> internal/cli: check for delete permissions before starting to prune

cmd/utils/flags.go
The `eth_getLogs` started to panic when it tried to fetch the chain config. This was because wrong instance of filter api was registered against the `eth` namespace which didn't have the config set during the upstream merge. This PR fixes that.
=> cmd/utils: use defined filter api instance instead of a new one

builder/files/config.toml, core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool_test.go, docs/cli/example_config.toml, docs/cli/server.md, eth/backend.go, eth/catalyst/api_test.go, eth/gasprice/gasprice.go, internal/cli/server/config.go, internal/cli/server/config_test.go, internal/cli/server/testdata/default.toml, miner/miner.go, miner/worker_test.go, packaging/templates/testnet-amoy/archive/config.toml, packaging/templates/testnet-amoy/sentry/sentry/bor/config.toml, packaging/templates/testnet-amoy/sentry/validator/bor/config.toml, packaging/templates/testnet-amoy/without-sentry/bor/config.toml, params/protocol_params.go
This PR extends on https://github.com/maticnetwork/bor/pull/1264 and makes the following changes:
1. The gas config enforcement value is modified to 25gwei (instead of 30gwei before)
2. The gas config enforcements are only made for Amoy network
3. Fixes a bug in TxPool gas tip enforcement where it wasn't honouring the enforced limit on non-validator nodes
Due to (2), the checks look a bit complicated but upon mainnet release, they'll be again simplified and generalised. PIP-35 for mainnet will be released later with prior announcements. 
- …
=> PIP-35 for amoy: enforce gas related configs

miner/test_backend.go, miner/worker.go
This PR logs the last transaction miner was processing before commit interrupt was called. This may be helpful in analysing the kind of transactions which might be taking longer time to process.
=> miner: log last tx hash before commit interrupt

builder/files/config.toml, core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool_test.go, docs/cli/example_config.toml, docs/cli/server.md, eth/backend.go, eth/catalyst/api_test.go, eth/gasprice/gasprice.go, internal/cli/server/command_test.go, internal/cli/server/config.go, internal/cli/server/config_legacy_test.go, internal/cli/server/config_test.go, internal/cli/server/testdata/default.toml, internal/cli/server/testdata/test.toml, miner/miner.go, miner/worker_test.go, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/testnet-v4/archive/config.toml, packaging/templates/testnet-v4/sentry/sentry/bor/config.toml, packaging/templates/testnet-v4/sentry/validator/bor/config.toml, packaging/templates/testnet-v4/without-sentry/bor/config.toml
This PR generalises the 25 gwei gas enforcement (based on [PIP-35](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-35.md)) to all networks (i.e. specifically polygon mainnet). Earlier, it was only introduced to amoy. This PR removes those checks such that it's applicable to mainnet as well. 
The values `txpool.pricelimit`, `miner.gasprice` and `gpo.ignoreprice` are now enforced to 25 gwei
Applicable to all
=> PIP-35: enforce gas related configs for mainnet

cmd/geth/main.go, consensus/bor/heimdallgrpc/client.go, go.mod, go.sum, internal/cli/command.go, internal/debug/flags.go
In this PR we remove `memsize` as it is incompatible with latest `go` versions, preventing the app to build in `docker`.
Same changes have been applied in `go-ethereum` [here](https://github.com/ethereum/go-ethereum/commit/e4675771eda550e7eeb63a8884816982c1980644#diff-30437b401e56caf63af6a19560e47ff5c65bfe20970c044d5c497f2158729b3c).
Also, the latest commit on this branch solves some `lint` issues.
=> internal/debug: remove memsize to fix docker

core/vm/evm.go, params/config.go, params/protocol_params.go
[PIP-30: increased max code size limit to 32KB](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-30.md)
=> PIP-30: increased max code size limit to 32KB

consensus/bor/api/caller.go, consensus/bor/contract/client.go, internal/ethapi/api.go
In the recent upstream merge,`CallWithState` was replaced with simple call. This PR reverts that. 
More context in this original PR: https://github.com/maticnetwork/bor/pull/883
=> consensus/bor: use CallWithState to fetch last state id

core/state/statedb_test.go
This change test a case when multiple reverts happen concurrently.
=> Add test for concurrent revert in MVHashmap

consensus/bor/bor.go
Add additional information about validator set when a mismatch between local contract and block header is observed.
=> Log info about mismatched valset

eth/filters/api.go
Fixes nil pointer dereference bug in filter.
Sample error:
```
ERROR[10-04|04:21:13.680] RPC method eth_getLogs crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 19346 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
/home/ubuntu/bor/rpc/service.go:216 +0x85
panic({0x26d2fa0?, 0x4f70000?})
/home/ubuntu/.go/src/runtime/panic.go:770 +0x132
github.com/ethereum/go-ethereum/eth/filters.(*FilterAPI).GetLogs(0xc006412f80, {0x3a5b4e8, 0xc0008e3720}, {0x0, 0xc009a33000, 0xc009a33020, {0x54b4880, 0x0, 0x0}, {0x0, ...}})
/home/ubuntu/bor/eth/filters/api.go:355 +0x5b
reflect.Value.call({0xc00e2795c0?, 0xc00e402c68?, 0x50?}, {0x2af2779, 0x4}, {0xc0008e3a40, 0x3, 0xc0008e3a40?})
/home/ubuntu/.go/src/reflect/value.go:596 +0xca6 …
```
=> Fix panic in eth_getLogs

internal/cli/server/server.go
In this PR we add default timeouts to prometheus server.
=> internal/cli: add prometheus sever timeouts

.github/workflows/rpm_amoy_profile_packager.yml, .github/workflows/rpm_arm_packager.yml, .github/workflows/rpm_mainnet_profile_packager.yml, .github/workflows/rpm_packager.yml
Added rpm packaging for arm and x86 builds
Added checksums
Added profiles for rpm builds using no arch( including pbss profiles ) 
Dependent on existing PR merge: https://github.com/maticnetwork/bor/pull/1311
- [x ] New feature (non-breaking change that adds functionality)
- [x ] I have added at least 2 reviewer or the whole pos-v1 team
- [ x] I have added sufficient documentation in code
- [ x] I have tested this code manually on local environment
Tested on arm64 and x86 nodes with rpm …
=> Adding rpm packagers

core/txpool/legacypool/legacypool.go, core/txpool/legacypool/list.go, core/txpool/legacypool/list_test.go
Added checks for block number and timestamp PIP15 options in the `FilterTxConditional` function. Without those, transactions with invalid block number/timestamp options are never demoted.
=> Check block number and timestamp options when filtering conditional transactions

cmd/utils/flags.go
This fixes the problem where bor's state sync log missing from filter logs.
=> Fix bor logs missing

ethstats/ethstats.go, ethstats/ethstats_test.go
This change addresses the panic issue when the block is nil in ethstats. Also added test that will catch this case in CI. 
=> Fix panic on nil block in ethstats

consensus/bor/heimdall/client.go
In this PR we provide a bytes limit for the heimdall API responses.
=> Limit bytes during response body read

eth/filters/IBackend.go, go.mod, go.sum, integration-tests/bor_health.sh, integration-tests/smoke_test.sh, internal/cli/server/api_service.go
In this PR we handle edge cases with string blockNumber
=> gRPC edge cases

.github/workflows/packager_deb.yml
In the building of the arm64, the binary copy step was not included. This causes an issue where the user can download the current arm64 binary package and it will install. Bor will then fail to execute because it is the wrong binary.
- [x ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ x] I have added at least 2 reviewer or the whole pos-v1 team
- [x ] I have added sufficient documentation in code
Please post …
=> Wrong architecture binary ended up in arm64

core/state/statedb.go, core/state/statedb_test.go
`CreateContract` was a new function introduced from upstream merge after v1.5.0. When `CreateContract` is called, it should also call `mvRecordWritten` to ensure the state object is in the live set of statedb. Otherwise, some information, e.g. balance of the account, might get lost in the rest of opcodes in that txn.
=> Fix incorrect balance when CreateContract is used in block-stm

consensus/bor/bor.go
When fetch validators from child chain contract, `rpc.LatestNumber` was used to make the `eth_call` request. This PR replaces it with using `header.ParentHash` so that the state being used while making the call belongs to the same fork as the block being imported and checked for.
=> consensus/bor: fetch validator set using parent hash

cmd/clef/intapi_changelog.md, docs/cli/server.md, p2p/simulations/README.md
This PR addresses several typographical issues across multiple documentation files. The changes include fixing hyphenation errors, correcting article usage, and updating duplicated phrases. 
- Fixed the spelling of "password-protected" in `intapi_changelog.md`.
- Corrected the use of "an" vs. "a" in `server.md` and `README.md` for consistency and clarity.
- Added missing hyphen in "cross-origin" in `server.md`.
- Removed duplicated phrase "to have" in `rules.md`.
No additional comments.
=> Fix typos and improve documentation across several files

core/state/statedb.go, internal/ethapi/api_test.go
This pull request fixes the broken feature where the entire storage set is overridden.
Originally, the storage set override was achieved by marking the associated account as deleted, preventing access to the storage slot on disk. However, since #29520, this flag is also checked when accessing the account, rendering the account unreachable.
A fix has been applied in this pull request, which re-creates a new state object with all account metadata inherited.
Cherry-picking fix from geth: https://github.com/ethereum/go-ethereum/pull/30185
- In …
=> core/state: fix SetStorage override behavior (#30185)

core/state/statedb.go
This will fix a hasher bug that was introduced in https://github.com/maticnetwork/bor/commit/a23701f2d4b824ff30885d2061f6f71a11710dfc
The error can occur when the hasher is used by more than one goroutine at the same time:
```
panic: runtime error: slice bounds out of range [:-5]
goroutine 41937862 [running]:
golang.org/x/crypto/sha3.(*state).Write(0xc0ae67eb60, {0xc0e01441e0?, 0x14, 0x2a42620?})
/root/go/pkg/mod/golang.org/x/crypto@v0.24.0/sha3/sha3.go:135 +0x255
github.com/ethereum/go-ethereum/crypto.HashData({0x7fb51c2a9a58, 0xc0ae67eb60}, {0xc0e01441e0, 0x14, 0x14})
/go/src/github.com/maticnetwork/bor/crypto/crypto.go:79 +0x6b
github.com/ethereum/go-ethereum/core/state.(*StateDB).getStateObject.func1(0xc17b255680)
/go/src/github.com/maticnetwork/bor/core/state/statedb.go:992 +0xfa …
```
=> Fix hasher

consensus/bor/bor.go, core/blockchain.go, core/state/statedb.go
Block execution contains the time it takes to fetch state sync data from heimdall, which sometimes returns data with long latency (> 1s). When the latency is significant, the chain execution time will be affected and become inaccurate. This PR isolate the time of heimdall requests from block execution.
Please complete this section with the steps you performed if you ran manual tests for this functionality, otherwise …
=> Make block execution timer more accurate

crypto/crypto.go
Use sync.Pool in Keccak hash operations to reduce memory allocations and GC pressure.
Performance impact:
- Reduced GC pressure: scanobject decreased from 20.43% to 2.59%
- Improved memory management: mallocgc reduced to 1.52% (7.38% cumulative)
- More efficient state operations with less GC overhead
- Transaction processing shows improved efficiency with less GC interference
While the core Keccak hash computation (keccakF1600) still takes 11.75% CPU time, the overall system performance has improved due to reduced memory allocation overhead and better GC characteristics.
**pprof before**
**pprof after**
=> Use sync.Pool for keccak state

core/rawdb/chain_iterator.go
Fixes https://github.com/maticnetwork/bor/issues/1387
When ancient data was pruned, the `iterateTransactions` function returned a nil channel causing the outer functions to not proceed leading to ungraceful shutdown. This PR handles the check for ancient pruner offset in outer functions. 
Please post additional comments in this section if you have them, otherwise …
=> core/rawdb: handle ancient pruner offset in indexing

core/txpool/legacypool/legacypool.go, core/txpool/legacypool/list.go
Improve txpool performance by removing redundant locks.
Most changes were from https://github.com/maticnetwork/bor/pull/604, which added the locks for deeper level of control when debugging.
runReorg used ~45% of CPU cycles. 
Usage of runReorg dropped to 12%.
=> Remove redundant locks from txpool

internal/cli/snapshot.go
Fix a bug that leads to node corruption when `--datadir.ancient` has a trailing `/`.
To reproduce:
```
/usr/bin/bor snapshot prune-block --datadir=/var/lib/polygon/bor/ --datadir.ancient=/var/lib/polygon/bor/bor/chaindata/ancient/
```
Behaviour:
* `bor` saves `ancient_back` to `/var/lib/polygon/bor/bor/chaindata/ancient/ancient_back` because of `filepath.Split` at line 485
* folder `ancient` is deleted after pruning, removing `ancient_back`
* -> node is corrupted
Fix: use `TrimSuffix` to remove the trailing `/` is present.
=> internal/cli: trim trailing / from ancient path

consensus/beacon/consensus.go, consensus/bor/bor.go, consensus/clique/clique.go, consensus/consensus.go, consensus/ethash/ethash.go, core/blockchain.go, miner/test_backend.go, miner/worker.go, tests/bor/helper.go
This PR removes open telemetry based tracing from the whole mining workflow. The tracing extended into consensus and core blockchain functions from miner is also removed in this PR. We weren't checking the tracing from a long time and the way it was implemented increased the code complexity a lot. As a replacement to get observability in mining, we can add more logs and metrics as a separate task. 
For mining related e2e tests, some functions were also modified in `miner/test_backend.go` to introduce artificial delays. The code was out of sync. This PR also brings it in sync with original `miner/worker.go` methods. 
In case this PR includes changes that must be applied only to a subset of nodes, …
=> miner, consensus, core: remove tracing in mining workflow

ethclient/bor_ethclient.go, ethclient/ethclient.go
Refer to previous PR: https://github.com/maticnetwork/bor/pull/1409
This PR resolves an issue where blocks containing system transactions could not be retrieved properly using `getBlock`.  
For such blocks, the `transactionsRoot` is set to `EmptyTxsHash`, but the `Transactions` list contains one transaction, which leads to a mismatch and prevents block information from being retrieved.  
The validation logic has been updated to handle these cases correctly.
Example block with system transaction: https://amoy.polygonscan.com/block/16653120
No breaking changes have been introduced in this PR.
This PR affects all nodes and does not include changes limited to a subset of nodes.
1. Retrieved a block with system transactions …
=> ethclient: handle single state-sync tx in get block calls

consensus/bor/bor.go
Reverts maticnetwork/bor#1384
The change was done to use state from previous header instead of the last canonical header as that was useful for side chain imports. Seems like even that can cause some issues. 
There were lot of peer drops recently on mainnet which led to this being the root cause. Whenever a chain is being imported, headers are sent to consensus engine for simple verification. 
https://github.com/maticnetwork/bor/blob/51af82cca11b4ccfec9bd967bc2e426eaf1417c0/core/blockchain.go#L2101
In consensus, verification happens in background as below
https://github.com/maticnetwork/bor/blob/51af82cca11b4ccfec9bd967bc2e426eaf1417c0/consensus/bor/bor.go#L317-L327
Header verification is supposed to be state-less (i.e. can be done independently without having any info of previous block …
=> Revert "consensus/bor: fetch validator set using parent hash"

miner/worker_test.go
Follow up to https://github.com/maticnetwork/bor/pull/1434
This PR adds a test which verifies the working of miner module when running on a sentry (non-validator) node. It tries to disable the normal mining flow and trigger it via the new transactions subscription channel and asserts mainly 2 things
- Interrupt commit works and breaks execution when the time crosses deadline (i.e. header.Timestamp)
- Mining is not triggered when we've already crossed the deadline 
It uses a bit unconventional / hacky way to do things (as we've to let the worker know midway that it's a sentry and explicitly disable normal commit work route to mine new blocks)
In case this PR includes changes that must be applied only …
=> miner: add commit interrupt tests for non-validator mode

consensus/bor/heimdall/client.go, go.mod, go.sum
This PR fixes retrieving of state sync events from heimdall(v2).
=> Fix state sync fetch

miner/worker_test.go
Fixes https://github.com/maticnetwork/bor/issues/1447
https://github.com/maticnetwork/bor/pull/1441 added new test for commit interrupt via new transactions channel. 
The results were non-deterministic and used to fail sometimes. This was because we use `w.current` to calculate the `delay` which needs to be correct for the test to work as expected. It takes a while before `w.current` is updated to the next block (block 3 in this case). This PR adds a small delay so that we have the new block and delays are accurately calculated for the test to work.
=> miner: wait for next block before running commit interrupt tests

core/state/reader.go
While syncing a node using the develop branch we found the following fatal error:
```
fatal error: concurrent map writes
goroutine 81880 [running]:
github.com/ethereum/go-ethereum/core/state.(*trieReader).Account(0xc063173ce0, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
/home/krishangshah/bor/core/state/reader.go:185 +0xac
github.com/ethereum/go-ethereum/core/state.(*multiReader).Account(0x0?, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
/home/krishangshah/bor/core/state/reader.go:279 +0x96
github.com/ethereum/go-ethereum/core/state.(*StateDB).getStateObject.func1(0xc031573340)
/home/krishangshah/bor/core/state/statedb.go:976 +0xd7
github.com/ethereum/go-ethereum/core/state.MVRead[...](0xc031573340?, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...) …
```
=> Bug fix: concurrent map writes

docs/cli/example_config.toml, docs/cli/server.md, eth/backend.go, eth/handler.go, eth/handler_eth_test.go, internal/cli/server/config.go, internal/cli/server/flags.go, internal/cli/server/testdata/default.toml, p2p/server.go, packaging/templates/mainnet-v1/archive/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml, packaging/templates/mainnet-v1/sentry/sentry/bor/pbss_config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/config.toml, packaging/templates/mainnet-v1/sentry/validator/bor/pbss_config.toml, packaging/templates/mainnet-v1/without-sentry/bor/config.toml, packaging/templates/mainnet-v1/without-sentry/bor/pbss_config.toml, packaging/templates/testnet-amoy/archive/config.toml, packaging/templates/testnet-amoy/sentry/sentry/bor/config.toml, packaging/templates/testnet-amoy/sentry/sentry/bor/pbss_config.toml, packaging/templates/testnet-amoy/sentry/validator/bor/config.toml, packaging/templates/testnet-amoy/sentry/validator/bor/pbss_config.toml, packaging/templates/testnet-amoy/without-sentry/bor/config.toml, packaging/templates/testnet-amoy/without-sentry/bor/pbss_config.toml, scripts/getconfig.go
Introducing `txannouncementonly` option.
When enabled, the node will gossip transactions to its peers via announcements only.
Default value is `false` (standard behavior).
This is a convenience option for validators who enable the Fastlane MEV protocol.
Validators participating in the Fastlane protocol have been patching their sentry nodes to achieve the same for more than 2 years. Allowing it as a standard parameter would greatly improve validators experience on each new Bor release.
=> param: transactions announced only

cmd/clef/run_test.go, cmd/utils/history_test.go, core/txpool/blobpool/blobpool_test.go, internal/cli/snapshot_test.go
TempDir() is a method introduced in Go 1.15 for testing.T. It automatically creates a temporary directory and cleans it up after the test is complete, eliminating the hassle of manually handling errors and cleanup. More detail about TempDir https://pkg.go.dev/testing#B.TempDir
The new pr for  https://github.com/maticnetwork/bor/pull/1482
Please post additional …
=> refactor: use t.TempDir() instead of os.MkdirTemp

eth/backend.go, eth/protocols/eth/discovery.go, eth/protocols/eth/handler.go, eth/protocols/snap/handler.go
Combination of https://github.com/ethereum/go-ethereum/pull/30302 and https://github.com/ethereum/go-ethereum/pull/31185 to fix the `p2p` issues we were facing.
=> eth: dial nodes from discv5

consensus/bor/bor.go, core/blockchain.go, core/headerchain.go, core/parallel_state_processor.go, core/state_processor.go, core/stateless.go, core/types.go, eth/catalyst/api.go, eth/state_accessor.go
Stateless execution is now functional. To support it, we clear parts of the block header, which prevents retrieving the original coinbase (author) since that field is part of the signed data. As a result, the author must now be explicitly provided to avoid incorrect values.
=> Stateless execution

consensus/bor/bor.go, consensus/bor/heimdall/span/spanner.go, consensus/bor/span.go, consensus/bor/span_mock.go
Related Fixes:
- Include witness StateDB on `GetCurrentSpan` call on stateless client
- Include state prefetching of `LastStateId` call on block producer 
- Tests made on Kurtosis, solution is open and running. But facing issues on syncing
=> Fix Span Committing on Stateless Client

docs/cli/example_config.toml, docs/cli/server.md, eth/handler.go, eth/sync.go, internal/cli/server/config.go, internal/cli/server/flags.go
This PR enables snap sync (for real this time). It allows users to use it as sync mode via setting the flag `syncmode` to `snap`. Snap sync instead of executing every block, downloads the state and chain from the p2p network trusting the peer(s) it's downloading from. More details about snap sync can be found [here](https://geth.ethereum.org/docs/fundamentals/sync-modes#snap-sync). 
Latest benchmarks shows syncing time of ~30 hours on polygon mainnet which is significantly better than full sync timings. 
- In case …
=> eth, internal/cli: allow bor to run in snap sync

core/state/reader.go, params/version.go
This is to fix hasher panic caused by a recent upstream merge.
```
/home/runner/work/bor/bor/core/state/reader.go:82 +0x6b
github.com/ethereum/go-ethereum/core/state.(*stateReader).Account(0xc101562400, {0xfb, 0xf8, 0xb7, 0xd2, 0xdd, 0x10, 0x44, 0x7d, 0xcb, ...})
/home/runner/work/bor/bor/crypto/crypto.go:92 +0x6b
github.com/ethereum/go-ethereum/crypto.HashData({0x7d7d9c1d3288, 0xc0b5bb81e0}, {0xc19359c558, 0x14, 0x14})
/home/runner/go/pkg/mod/golang.org/x/crypto@v0.31.0/sha3/sha3.go:117 +0x1c5
golang.org/x/crypto/sha3.(*state).Write(0xc138702f70?, {0xc19359c558?, 0x14?, 0x29edcc0?})
goroutine 362766824 [running]:
panic: sha3: Write after Read
```
In case this PR includes changes that must be applied …
=> [bug fix] Avoid concurrent access to hasher buffer

consensus/bor/bor.go, consensus/bor/bor_test.go
We call the `IntermediateRoot` function in `Finalize` method of consensus while validating a remote block. We update the `header.Root` to the result of the call which is useless as we're only operating on a copy of header. Moreover, we're not supposed to update the state root while validating a block. We only need to compare our local state root with the one present in header. 
This PR removes that call as it's unnecessary. We anyways make this call later when we're validating the state after processing the transactions. 
- In case link the …
=> consensus/bor: remove state root calculation from bor consensus

internal/cli/server/config.go, miner/miner.go
[PIP-60](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-60.md): Increase gas limit to 45M
=> PIP-60: Increase gas limit to 45M

core/blockchain.go, eth/bor_checkpoint_verifier.go, eth/downloader/beaconsync.go, eth/downloader/bor_downloader.go, eth/handler.go, eth/sync.go
Implement a one-time fast-forward in the stateless client (bor-connected heimdall-v1) for tests by setting TotalDifficulty to the target block number on startup instead of fetching real TD and skipping formal validations. If it ever desyncs, simply restart to rerun the fast-forward.
=> FastForward on HeimdallV1

eth/api_backend.go, internal/ethapi/api.go, internal/ethapi/api_test.go, internal/ethapi/backend.go, internal/ethapi/transaction_args_test.go
The implemented method returns the `totalDifficulty` given a block number. The main goal is allow heimdall querying the Total Difficulty of a produced block when building a milestone.
=> eth_getTdByNumber method

consensus/bor/bor.go
TL;DR
https://0xpolygon.slack.com/archives/C03PD53G8L9/p1748858685398169
Before:
```bash
INFO "✅ Committing new span"                id=1                startBlock=256 endBlock=1855 validatorBytes=dad9018227109459425e069c8143bf456506d670c900a713bd836a producerBytes=dad9018227109459425e069c8143bf456506d670c900a713bd836a
INFO "✅ Committing new span"                id=1                startBlock=256 endBlock=1855 validatorBytes=dad9018227109459425e069c8143bf456506d670c900a713bd836a producerBytes=dad9018227109459425e069c8143bf456506d670c900a713bd836a
ERROR message execution failed on contract     err="execution reverted"
```
After:
```bash
INFO  "✅ Committing new span"                id=1                startBlock=256 endBlock=1855 validatorBytes=dad9018227109459425e069c8143bf456506d670c900a71 …
```
=> fix(consensus, span): avoid duplicate span commit for spanId 1

cmd/geth/chaincmd.go, cmd/utils/flags.go, cmd/utils/history_test.go, consensus/bor/bor.go, core/blockchain_repair_test.go, core/blockchain_sethead_test.go, core/blockchain_snapshot_test.go, core/blockchain_test.go, core/rawdb/accessors_chain_test.go, core/rawdb/database.go, core/state/pruner/pruner.go, core/txindexer_test.go, eth/backend.go, eth/downloader/bor_downloader.go, eth/downloader/bor_downloader_test.go, internal/cli/snapshot.go, internal/cli/snapshot_test.go, node/database.go, node/node.go, triedb/pathdb/database_test.go
Freeze db has a check when it founds it as empty while the head hash is not matching the genesis hash. In this scenario geth checks if #1 block exists or not on database. This fix allows this scenario for stateless client since this client usually fast forward the block #1.
=> Fix ancient pruning check on stateless start

.github/workflows/ci.yml, consensus/bor/api.go, consensus/bor/bor.go, consensus/bor/errors.go, consensus/bor/heimdall.go, consensus/bor/heimdall/client.go, consensus/bor/heimdall/client_test.go, consensus/bor/heimdall/metrics.go, consensus/bor/heimdallgrpc/span.go, consensus/bor/snapshot.go, consensus/bor/span_store.go, consensus/bor/span_store_test.go, eth/backend.go, eth/handler_bor_test.go, go.mod, go.sum, internal/cli/server/config.go, internal/cli/server/testdata/default.toml, miner/fake_miner.go, miner/worker.go, miner/worker_test.go, params/config.go, tests/bor/bor_test.go, tests/bor/mocks/IHeimdallClient.go
This PR introduces VeBlop span rotation.
Major changes:
* Today, each span is deterministically written to a contract for future blocks. After VeBlop, the span will be proactively retrieved from heimdall when the current block producer fails to deliver new blocks within a certain time range, which is currently set at 4s. 
* Remove span commit and validator set info in header after VeBlop, since the span info will be always retrieved from heimdall dynamically.
A HF block number is introduced.
Please complete this section with the steps you performed if you ran manual tests …
=> VeBlop span rotation

eth/bor_checkpoint_verifier.go, params/version.go
When checkpoint verifier inserts canonical chain after rewind, the fork choice logic in writeBlockAndSetHead() may determine that no reorg is needed, causing blocks to be inserted with SideStatTy instead of CanonStatTy. This prevents writeHeadBlock() from being called, leaving canonical hash mappings outdated.
The issue manifests as:
- "Successfully inserted canonical chain" log appears
- GetBlockByNumber() still returns old block hash
- Fork detection triggers false positives for whitelisted blocks
- Milestone reorg protection fails
Fix by explicitly calling SetCanonical() after InsertChain() to force canonical status and ensure proper canonical hash mapping updates.
Please complete this section if any breaking changes …
=> eth: fix canonical chain state inconsistency in checkpoint verifier

consensus/bor/bor.go, params/config.go, params/config_test.go
Added OverrideStateSyncRecordsInRange to overwrite the state sync records for a range of blocks.
=> consensus/bor, params: added OverrideStateSyncRecordsInRange to overwrite the state sync records for a range of blocks

core/blockchain.go, core/blockchain_test.go, core/rawdb/accessors_metadata.go, core/rawdb/schema.go, core/state/statedb.go, core/stateless.go, core/stateless/database.go, core/stateless/database_test.go, core/stateless/encoding.go, eth/backend.go, eth/catalyst/api.go, eth/downloader/bor_downloader.go, eth/downloader/bor_downloader_test.go, eth/downloader/modes.go, eth/fetcher/block_fetcher.go, eth/fetcher/witness_manager.go, eth/fetcher/witness_manager_test.go, eth/peer.go, eth/protocols/snap/sync.go, eth/protocols/snap/sync_test.go, eth/protocols/wit/dispatcher.go
This PR mainly adds the ability to download all historical bytecode before starting stateless sync.
Also included a few improvements and bug fixes for stateless sync.
=> Stateless sync bytecode cache

internal/cli/server/api_service.go, internal/cli/server/command.go, internal/cli/server/helper.go, internal/cli/server/server.go
This PR fixes a bug of a time window at startup which `s.backend == nil`, which causes panic in any GRPC call if enabled by heimdall and queried right after starting bor.
It was reported on this [issue](https://github.com/maticnetwork/bor/issues/1632)
=> Start GRPC server after backend assignment

.github/workflows/amoy_deb_profiles.yml, .github/workflows/mainnet_deb_profiles.yml
This PR aims to start uploading our genesis in our assets page so users can use it as the source of truth. Currently we faced an issue (https://github.com/maticnetwork/bor/issues/1618) where we updated the genesis and the hash mismatches the file on a tutorial. With this we can instruct users on trusting directly on the checksum from github.
=> Upload genesis as assets on releases

core/txpool/blobpool/blobpool.go, core/txpool/blobpool/blobpool_test.go, core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool_test.go, core/txpool/subpool.go, core/txpool/txpool.go, eth/api_backend.go, eth/catalyst/simulated_beacon.go, eth/handler.go, eth/handler_test.go, eth/sync.go, miner/ordering.go, miner/ordering_test.go, miner/worker.go, miner/worker_test.go
Use commit interrupt for fill transactions as well. 
We interrupt executing new transactions when the 2s block time mark is crossed. Although before execution, we call `Pending()` function of transaction pool which can be time consuming in some cases. If the 2s time limit is up, we'd like to interrupt that call as well to avoid spending any more time on doing any work for this block.
This PR passes the `interrupt` atomic boolean (which is used across the modules to trigger interrupt) when we're fetching the pending transactions and sorting them based on nonce and fee before executing. 
In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it …
=> core, eth, miner: interrupt block building during fill transactions incase of timeout

Dockerfile, go.mod
Switched to pinned Go 1.24 & Alpine 3.22; used a two‑stage BuildKit build with cache+SSH mounts to compile, then copied only the bor binary into a tiny Alpine runtime (just certs, no toolchain or Bash)—slashing the image from gigabytes to a few hundred megabytes.
This mirrors exactly what Geth’s Dockerfile does; see their approach here:
https://github.com/ethereum/go-ethereum/blob/master/Dockerfile
=> Dockerfile: use multi-stage build optimisation

eth/downloader/bor_downloader_test.go, eth/downloader/bor_fetchers_concurrent.go, eth/downloader/bor_fetchers_concurrent_witnesses.go, eth/downloader/peer.go, eth/downloader/skeleton_test.go, eth/peer.go
This change will avoid sending witness request to peers that don't support `wit` protocol. Also fixes a sync issue where witness queue is hanging due to the node is incorrectly waiting for peers that don't support `wit` protocol.
=> Stateless sync fix wit download

core/txpool/legacypool/legacypool.go, miner/worker.go
Adds some observability to capture delays during block building. Mainly captures
1. Time taken to acquire lock in pending pool
2. Time taken for the whole pending call to finish (this matters the most for miner during block building)
3. Time taken to release the lock held during tx pool reorg
4. Time taken to init a heap out of the pending transactions before starting to execute transactions
5. Time taken to actually execute transactions in ideal mining workflow
Please complete this …
=> core/miner: observability for block building delays

go.mod, go.sum
Since we merged [this](https://github.com/0xPolygon/heimdall-v2/pull/420) PR using a squash merge, the `d58ce649f932` commit was lost, and a new commit was created instead. This PR fixes that using the latest commit on the `develop` branch of heimdall-v2.
Error:
```bash
make bor
mkdir -p /Users/krishangshah/go/bin/
go build -o /Users/krishangshah/polygon/bor/build/bin/bor -ldflags "-X github.com/ethereum/go-ethereum/params.GitCommit=af0b8f5e5a300b01a1accb8b4d9ec3ffa21c1a14" ./cmd/cli/main.go
go: downloading github.com/0xPolygon/heimdall-v2 v0.2.16-beta.0.20250806140653-d58ce649f932
go: github.com/0xPolygon/heimdall-v2@v0.2.16-beta.0.20250806140653-d58ce649f932: invalid version: unknown revision d58ce649f932
make: *** [bor] Error 1
```
=> fix: build

eth/protocols/eth/broadcast.go
Found issue:
```
Jul 23 16:20:22 polygon-mainnet bor.sh[1563]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 23 16:20:22 polygon-mainnet bor.sh[1563]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1c3f99c]
Jul 23 16:20:22 polygon-mainnet bor.sh[1563]: goroutine 177336300 [running]:
Jul 23 16:20:22 polygon-mainnet bor.sh[1563]: github.com/ethereum/go-ethereum/core/types.(*Transaction).GetOptions(...)
Jul 23 16:20:22 polygon-mainnet bor.sh[1563]:         /bor/core/types/transaction.go:120
Jul 23 16:20:22 polygon-mainnet bor.sh[1563]: github.com/ethereum/go-ethereum/eth/protocols/eth.(*Peer).announceTransactions(0xc1565eb110)
Jul 23 16:20:22 polygon-mainnet bor.sh[1563]:         /bor/eth/protocols/eth/broadcast.go:161 +0x53c
Jul 23 16:20:22 …
```
=> eth/protocols: add nil check for tx before calling GetOptions

eth/backend.go, eth/sync.go, ethstats/ethstats.go
After the last issue occurred on Bor, a few nodes reported some crashes because of the reorgs. This PR address some of those issues by better logging and including a few more nil checks.
=> Improving fail handling from reorgs

cmd/geth/dbcmd.go, cmd/utils/flags.go
ref https://polygon.atlassian.net/browse/POS-3035
This is the updated response from `posdevnodes-mainnet-bor-2`:
```bash
~/bor$ sudo go run ./cmd/geth db metadata --datadir /var/lib/bor/data/
INFO [08-21|09:50:40.491] Maximum peer count                       ETH=50 total=50
INFO [08-21|09:50:40.492] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-21|09:50:40.495] Set global gas cap                       cap=50,000,000
INFO [08-21|09:50:40.495] Initializing the KZG library             backend=gokzg
INFO [08-21|09:50:40.702] Using pebble as the backing database
INFO [08-21|09:50:40.702] Allocated cache and file handles         database=/var/lib/bor/data/bor/chaindata cache=512.00MiB handles=524,288
INFO [08-21|09:50:42.220] …
```
=> fix: dbcmd

eth/peer.go, eth/peer_test.go
Fixes #1727 
This PR fixes the nil pointer dereference panic reported that occurs when `RequestWitnesses` tries to access `lastWitRes.Meta`, after receiving no usable witness data.
When no witness responses are received (due to peer disconnection, empty responses, or processing failures), the witness response loop never executes or processes no valid data, leaving `lastWitRes` as nil. The code then panics when trying to access `lastWitRes.Meta` and `lastWitRes.Time`.
=> eth/peer(wit): fix nil pointer dereferences in RequestWitnesses

core/rawdb/milestone.go, docs/cli/README.md, docs/cli/purge-whitelisted-entries.md, eth/downloader/whitelist/finality.go, eth/downloader/whitelist/milestone.go, eth/downloader/whitelist/service.go, eth/handler_bor.go, internal/cli/command.go, internal/cli/purge_whitelisted_entries.go
This PR
- Adds a new `bor purge-whitelisted-entries` sub command in cli which can purge all local whitelisted entries for checkpoint and milestone. 
- Adds a bypass logic to skip importing and validating against an incorrect milestone
- Skip loading milestones or checkpoints if local entry is corrupted (i.e. empty hash)
Please post additional comments in this …
=> Purge whitelisted entries and bypass validation for incorrect milestone

eth/bor_checkpoint_verifier.go
When a milestone doesn't match a local block, we should return an hash mismatch error, so the milestone would be kept for future evaluation.
This error returning was there in [`v2.0.1`](https://github.com/0xPolygon/bor/blob/909b764305fb98386d20a6181bbaa0c477100556/eth/bor_checkpoint_verifier.go#L134C3-L134C31), but maybe somehow got lost in merging.
Please post …
=> fix: return hash mismatch error properly

core/txpool/legacypool/list.go
Avoid using negative cap while initialising array in Discard. 
=> core/txpool/legacypool: avoid using negative cap in discard

consensus/bor/heimdall/client.go, consensus/bor/span_store.go, consensus/bor/span_store_test.go
This commit fixes a bug where when heimdall is down, its status isn't correctly reflected in span store, resulting bor to continue sync/mine blocks. The fix will make `FetchStatus` and `GetLatestSpan` non-blocking, which would allow the status of heimdall to be properly updated in span store, and make `waitUntilHeimdallIsSynced` wait when heimdall is down.
=> [bugfix] Update heimdall status correctly

consensus/bor/api.go
Use the correct block number for retrieving the snapshot. This is change is required because the behavior  of `snapshot()` in bor consensus had changed. Before, it was expecting the caller to pass the parent block of the target block, but now it is expecting the target block to be directly passed in.
Tested in a devnode.
=> Fix getSnapshotProposerSequence

eth/fetcher/block_fetcher.go, eth/fetcher/block_fetcher_race_test.go, eth/fetcher/witness_manager.go, eth/fetcher/witness_manager_test.go
If a peer announces a witness but responds an empty witness on a request, the peer will be deemed bad and get dropped immediately. This change will simplify the logic of witness manager and make the stateless node more resistant to bad peer behaviors.
=> Drop a peer immediately on receiving empty witness
